#!/bin/bash
###SHELLPACK preamble netpipe-install 3.7.2
WEB_LOCATION=http://bitspjoule.org/netpipe/code
MIRROR_LOCATION="$WEBROOT/proprietary/netpipe/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch NetPIPE-${VERSION}.tar.gz netpipe-${VERSION}-installed

###SHELLPACK build_start netpipe-${VERSION}-installed
###SHELLPACK make tcp

echo netpipe installed successfully
