#!/bin/bash
###SHELLPACK preamble starve-install 0
WEB_LOCATION="http://www.hpl.hp.com/research/linux/kernel/prog/test-starve.c"
MIRROR_LOCATION="$WEBROOT/starve/test-starve.c"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

cd $SHELLPACK_SOURCES || die Sources directory does not exist
rm -rf starve-${VERSION}-installed
mkdir -p starve-${VERSION}-installed

sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/starve-${VERSION}-installed/test-starve.c
cd $SHELLPACK_SOURCES/starve-${VERSION}-installed

gcc -O2 test-starve.c -o test-starve
if [ $? -ne 0 ]; then
	die "$P: Failed to build starve"
fi

exit $SHELLPACK_SUCCESS
