#!/bin/bash

###SHELLPACK preamble specjbb2015-install 1.00
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/spec"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

mkdir -p $SHELLPACK_SOURCES/specjbb2015-${VERSION}-installed/config
sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/SPECjbb2015_${VERSION}.zip $SHELLPACK_SOURCES/SPECjbb2015_${VERSION}.zip
cd $SHELLPACK_SOURCES
unzip SPECjbb2015_${VERSION}.zip || die Failed to unzip SPECjbb2015_${VERSION}.zip
mv SPECjbb2015_${VERSION} specjbb2015-${VERSION}-installed || die Failed to rename specjbb2015 directory

exit $SHELLPACK_SUCCESS
