#!/bin/bash

###SHELLPACK preamble specjbb2015-install 1.04
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/proprietary/spec"

for PACKAGE in $SPECJBB_PACKAGES; do
        install-depends $PACKAGE
done

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch SPECjbb2015-${VERSION}.tar.gz specjbb2015-${VERSION}-installed

exit $SHELLPACK_SUCCESS
