#!/bin/bash

###SHELLPACK preamble klp-bench 0

SCHBENCH_ITERATIONS=1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK check_install_required klp-${VERSION}
###SHELLPACK init_complete

./run.sh 2>&1 | tee $LOGDIR_RESULTS/klp.log

exit $SHELLPACK_SUCCESS
