#!/bin/bash
# wikibench installer

###SHELLPACK preamble wikibench 0.3.1
WEB_LOCATION=http://www.wikibench.eu/wp-content/uploads/2011/01
MIRROR_LOCATION=$WEBROOT/wikibench
MEDIAWIKI_VERSION=1.18.6

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

install-depends ant

. $SHELLPACK_INCLUDE/common.sh

###SHELLPACK check_external_install_required mediawikibuild mediawikibuild-${MEDIAWIKI_VERSION} ${MEDIAWIKI_VERSION}
###SHELLPACK sources_fetch wikibench-${VERSION}.tar.gz wikibench-${VERSION}-installed

echo wikibench installed successfully
