#!/bin/bash
# wikibench installer

###SHELLPACK preamble wikibench 0.3.1
WEB_LOCATION=http://www.wikibench.eu/wp-content/uploads/2011/01
MIRROR_LOCATION=$WEBROOT/wikibench
MEDIAWIKI_VERSION=1.18.6

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

install-depends ant

. $SHELLPACK_INCLUDE/common.sh

if [ ! -e $SHELLPACK_SOURCES/mediawiki-build-${MEDIAWIKI_VERSION}-installed ]; then
	echo Installing mediawiki and httpd server
	$SHELLPACK_INCLUDE/shellpack-install-mediawikibuild -v ${MEDIAWIKI_VERSION} || die Failed to install mediawiki httpd
	echo Mediawiki and httpd server successfully installed.
fi

###SHELLPACK sources_fetch wikibench-${VERSION}.tar.gz wikibench-${VERSION}-installed

echo wikibench installed successfully
