#!/bin/bash
###SHELLPACK preamble dedup-install 0
GIT_LOCATION=https://github.com/davidlohr/ezdedup.git
MIRROR_LOCATION="$WEBROOT/ezdedup/"

install-depends libopenssl-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch dedup-${VERSION}.tar.gz dedup-${VERSION}-installed

###SHELLPACK build_start dedup-${VERSION}-installed

###SHELLPACK self_extract signed-fix.patch
###SHELLPACK self_extract timeout-fix.patch

for FILE in signed-fix.patch timeout-fix.patch; do
	cat $SHELLPACK_TEMP/${FILE} | patch -p1 || exit $SHELLPACK_FAILURE
done

###SHELLPACK make

echo dedup installed successfully
exit $SHELLPACK_SUCCESS

==== BEGIN signed-fix.patch ====
diff --git a/encoder.c b/encoder.c
index 3b86743e8f81..58314d6d3936 100644
--- a/encoder.c
+++ b/encoder.c
@@ -163,7 +163,7 @@ static void print_stats(stats_t *s) {
 
   //determine most suitable unit to use
   for(unit_idx=0; unit_idx<unit_str_size; unit_idx++) {
-    unsigned int unit_div_next = unit_div * 1024;
+    size_t unit_div_next = unit_div * 1024;
 
     if(s->total_input / unit_div_next <= 0) break;
     if(s->total_dedup / unit_div_next <= 0) break;
==== END signed-fix.patch ====

==== BEGIN timeout-fix.patch ====
diff --git a/queue.c b/queue.c
index 823fdc000d05..ec8ce0022d58 100644
--- a/queue.c
+++ b/queue.c
@@ -1,4 +1,5 @@
 #include <assert.h>
+#include <sys/time.h>
 
 #include "util.h"
 #include "queue.h"
@@ -86,8 +87,16 @@ int queue_enqueue(queue_t *que, ringbuffer_t *buf, int limit) {
 #ifdef ENABLE_PTHREADS
   pthread_mutex_lock(&que->mutex);
   assert(!queue_isTerminated(que));
-  while (ringbuffer_isFull(&que->buf))
-    pthread_cond_wait(&que->notFull, &que->mutex);
+  while (ringbuffer_isFull(&que->buf)) {
+    struct timeval currentTime;
+    struct timespec timeout;
+
+    gettimeofday(&currentTime, NULL);
+    timeout.tv_sec = currentTime.tv_sec + 5;
+    timeout.tv_nsec = currentTime.tv_usec * 1000UL;
+
+    pthread_cond_timedwait(&que->notFull, &que->mutex, &timeout);
+  }
 #else
   assert(!queue_isTerminated(que));
 #endif
==== END timeout-fix.patch ====
