#!/bin/bash
###SHELLPACK preamble dedup-install 0
GIT_LOCATION=https://github.com/davidlohr/ezdedup.git
MIRROR_LOCATION="$WEBROOT/ezdedup/"

install-depends libopenssl-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch dedup-${VERSION}.tar.gz dedup-${VERSION}-installed

###SHELLPACK build_start dedup-${VERSION}-installed
###SHELLPACK make

echo dedup installed successfully
