#!/usr/bin/perl -wn
# Print out the max of a set of data read from standard in

$x[$i++] = $_;
$max=$x[0];
END {
	# Calculate mean
	for ($j = 1; $j < $i; $j++) {
		if ($x[$j] > $max) {
			$max = $x[$j];
		}
	}
	print $max;
}
