#!/usr/bin/perl -wn
# Print out the min of a set of data read from standard in

$x[$i++] = $_;
$min=$x[0];
END {
	if (! defined $i) {
		print "nan";
		exit;
	}

	# Calculate mean
	for ($j = 1; $j < $i; $j++) {
		if ($x[$j] < $min) {
			$min = $x[$j];
		}
	}
	print $min;
}
