#!/usr/bin/perl -wn
# Print out the quartiles of data read from standard in

use FindBin qw($Bin);
use lib "$Bin/lib/";
use VMR::Stat;

$x[$i++] = $_;
END {
	$i = 0;
	$quartiles = calc_quartiles(@x);
	$mean = calc_mean(@x);
	$stddev = calc_stddev(@x);
	$range = $$quartiles[3] - $$quartiles[1];
	print "$$quartiles[1] $$quartiles[2] $$quartiles[3]";
}
