FINEGRAINED_SUPPORTED=yes
NAMEEXTRA=

run_bench() {
	if [ "$THP_AVAILABILITY_READ_DEVICE" != "" ]; then
		READ_DEVICE="--read-device $THP_AVAILABILITY_READ_DEVICE"
	fi
	if [ "$THP_AVAILABILITY_READ_FILE" != "" ]; then
		READ_FILE="--read-file $THP_AVAILABILITY_READ_FILE"
	fi
	$SHELLPACK_INCLUDE/shellpack-bench-thpavail \
		$READ_DEVICE $READ_FILE \
		--write-device $THP_AVAILABILITY_WRITE_DEVICE \
		--filesystem $THP_AVAILABILITY_WRITE_FILESYSTEM \
		--iterations $THP_AVAILABILITY_ITERATIONS
}
