#!/bin/bash
# iperf3 installer
###SHELLPACK preamble iperf3-install 3.14
WEB_LOCATION=https://github.com/esnet/iperf/archive/refs/tags
MIRROR_LOCATION="$WEBROOT/iperf3"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch ${VERSION}.tar.gz iperf3-${VERSION}

###SHELLPACK build_start iperf3-${VERSION}
###SHELLPACK build_configure iperf3-${VERSION}
###SHELLPACK make_make_install

echo iperf3 installed successfully
