LIBHUGETLBFS_ROOT=$SHELLPACK_SOURCES/libhugetlbfs-${LIBHUGETLBFS_VERSION}-installed
LIBHUGETLBFS_LD=$LIBHUGETLBFS_ROOT/share/libhugetlbfs
LIBHUGETLBFS_LIBPATH=$LIBHUGETLBFS_ROOT/lib:$LIBHUGETLBFS_ROOT/lib64
LIBHUGETLBFS_LINK_OPTIONS="-B $LIBHUGETLBFS_LD -Wl,--hugetlbfs-link=BDT -Wl,--library-path=$LIBHUGETLBFS_ROOT/lib -Wl,--library-path=$LIBHUGETLBFS_ROOT/lib64"

install-depends libhugetlbfs
