#!/bin/bash
# This script installs memcached and leaves it ready for benchmarking
P=memcached-bench
DEFAULT_VERSION=1.4.13
. $SHELLPACK_INCLUDE/common.sh
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

install-depends libevent-devel

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=
SERVERSIDE_COMMAND=none
SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--serverside-command)
		SERVERSIDE_COMMAND=$2
		shift 2
		;;
	--serverside-name)
		SERVERSIDE_NAME=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

INSTALL_SWITCH=
if [ "$INSTALL_ONLY" = "yes" ]; then
	INSTALL_SWITCH=--install-only
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/memcached-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/memcached-${VERSION}-installed ]; then
	mmtests_activity source-install
	$SHELLPACK_INCLUDE/shellpack-install-memcached -v ${VERSION} $INSTALL_SWITCH || die memcached install script returned error
	mmtests_activity source-installed
fi
cd $SHELLPACK_SOURCES/memcached-${VERSION}-installed || die Failed to cd to memcached install directory

echo memcached successfully installed
exit $SHELLPACK_SUCCESS
#### Description memcached installer
#### Details memcached-bench 25
