#!/bin/bash
P=dbench-bench
DEFAULT_VERSION=3.04
. $SHELLPACK_INCLUDE/common.sh

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/dbench-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/dbench-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-dbench -v ${VERSION}  || die dbench install script returned error
fi
cd $SHELLPACK_SOURCES/dbench-${VERSION}-installed || die Failed to cd to dbench install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo dbench installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

if [ "$DBENCH_OSYNC" = "yes" ]; then
	DBENCH_OSYNC_COMMAND=-s
fi
if [ "$DBENCH_SYNC_DIRECTORY" = "yes" ]; then
	DBENCH_SYNC_COMMAND=-S
fi
if [ "$DBENCH_FSYNC" = "yes" ]; then
	DBENCH_FSYNC_COMMAND=-F
fi

DBENCH_CLIENTS=`echo $DBENCH_CLIENTS | tr ',' ' '`

CLIENT=1
while [ $CLIENT -le $DBENCH_MAX_CLIENTS ]; do
	monitor_pre_hook $LOGDIR_RESULTS $CLIENT
	./bin/dbench $DBENCH_OSYNC_COMMAND $DBENCH_SYNC_COMMAND $DBENCH_FSYNC_COMMAND \
		-D $TESTDISK_DIR \
		-t $DBENCH_DURATION \
		$CLIENT 2>&1 | tee $LOGDIR_RESULTS/dbench-$CLIENT.log \
			|| die Failed to run dbench
	monitor_post_hook $LOGDIR_RESULTS $CLIENT
	if [ $CLIENT -le $NUMCPUS ]; then
		CLIENT=$((CLIENT*2))
	else
		CLIENT=$((CLIENT*8))
	fi
done

exit $SHELLPACK_SUCCESS
#### Description dbench
#### Details dbench-bench 17
