#!/bin/bash
# This script installs getpidbench and whatever
P=getpidbench-bench
DEFAULT_VERSION=0
. $SHELLPACK_INCLUDE/common.sh
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=
SERVERSIDE_COMMAND=none
SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--serverside-command)
		SERVERSIDE_COMMAND=$2
		shift 2
		;;
	--serverside-name)
		SERVERSIDE_NAME=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/getpidbench
fi
if [ ! -d $SHELLPACK_SOURCES/getpidbench-installed ]; then
	mmtests_activity source-install
	$SHELLPACK_INCLUDE/shellpack-install-getpidbench -v ${VERSION}  || die getpidbench install script returned error
	mmtests_activity source-installed
fi
cd $SHELLPACK_SOURCES/getpidbench-${VERSION}-installed || die Failed to cd to getpidbench install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo getpidbench installed only as requested.
	exit $SHELLPACK_SUCCESS
fi
# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
eval $MMTESTS_NUMACTL ./getpidbench 2>&1
monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
exit $SHELLPACK_SUCCESS
#### Description sys_getpid in loop benchmark
#### Details getpidbench-bench 31
