#!/bin/bash
# This script whatevers memcachetest
P=memcachetest-bench
DEFAULT_VERSION=1
. $SHELLPACK_INCLUDE/common.sh

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	--threads)
		MEMCACHETEST_CONCURRENCY=$2
		shift 2
		;;
	--duration)
		MEMCACHETEST_DURATION=$2
		shift 2
		;;
	--memcached-mempool)
		MEMCACHED_MEMPOOL=$2
		shift 2
		;;
	--value-size)
		MEMCACHED_VALUE_SIZE=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/memcachetest-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/memcachetest-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-memcachetest -v ${VERSION}  || die memcachetest install script returned error
fi
cd $SHELLPACK_SOURCES/memcachetest-${VERSION}-installed || die Failed to cd to memcachetest install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo memcachetest installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

if [ "$MEMCACHED_MEMPOOL" = "" ]; then
	die Must specify memcached memory pool size
fi

# Start memcached server
$SHELLPACK_INCLUDE/shellpack-install-memcached --mempool $MEMCACHED_MEMPOOL
if [ $? -ne 0 ]; then
	die Failed to start memcached server
fi

# Fire this sucker up
cd $SHELLPACK_SOURCES/memcachetest-${VERSION}-installed || die Failed to cd to memcachetest directory
MEMCACHETEST_ITEMS=$(($MEMCACHED_MEMPOOL/($MEMCACHETEST_VALUE_SIZE+4096)))

echo Starting memcachetest client $MEMCACHETEST_CONCURRENCY
echo o $MEMCACHED_MEMPOOL memcached pool
echo o $MEMCACHETEST_CONCURRENCY concurrent requests
echo o $MEMCACHETEST_VALUE_SIZE value size
echo o $MEMCACHETEST_DURATION second duration
echo o $MEMCACHETEST_ITEMS items per iteration

./bin/memcachetest \
	-h 127.0.0.1 \
	-t $MEMCACHETEST_CONCURRENCY \
	-F -M $MEMCACHETEST_VALUE_SIZE \
	-i $MEMCACHETEST_ITEMS \
	-T $MEMCACHETEST_DURATION -l \
		    | tee $LOGDIR_RESULTS/memcachetest.log

$SHELLPACK_INCLUDE/shellpack-install-memcached --shutdown

exit $SHELLPACK_SUCCESS
#### Description memcachetest
#### Details memcachetest-bench 15
