#!/bin/bash
P=nas-install
DEFAULT_VERSION=3.3
. $SHELLPACK_INCLUDE/common.sh
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/nas/"

install-depends gcc-fortran

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

cd $SHELLPACK_SOURCES || die Sources directory does not exist
rm -rf NPB3.3

# Unconditionally fetch the tar to find out the real version number
TARFILE=NPB${VERSION}.tar.gz
sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
        error "$P: tar xf NPB${VERSION}.tar.gz failed"
        popd > /dev/null
        exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR nas-$VERSION-installed
pushd nas-$VERSION-installed > /dev/null || die Failed to rename tar

exit $SHELLPACK_SUCCESS
#### Description NAS Parallel Benchmark
#### Details nas 41
