#!/bin/bash
# This script installs fsmark and runs the regression tests

P=fsmark-bench
VERSION=3.3
NUM_THREADS=1
NUMCPUS=`grep processor /proc/cpuinfo | wc -l`
NUM_CPU_THREADS=1
NUM_DIRECTORIES=100
NUM_FILES_PER_DIRECTORY=25000
NUM_FILES_PER_ITERATION=50000
NUM_ITERATIONS=63
FILESIZE=0
CPU_FACTOR=1
. $SHELLPACK_INCLUDE/common.sh

# Basic args parser
while [ "$1" != "" ]; do
	case "$1" in
		-v)
			VERSION=$2
			shift 2;;
		--threads)
			NUM_THREADS=$2
			shift 2
			;;
		--threads-per-cpu)
			NUM_CPU_THREADS=$2
			NUM_THREADS=$(($NUM_CPU_THREADS*$NUMCPUS))
			shift 2
			;;
		--filesize)
			FILESIZE=$2
			shift 2
			;;
		--nr-files-per-iteration)
			NUM_FILES_PER_ITERATION=$2
			shift 2
			;;
		--nr-files-per-directory)
			NUM_FILES_PER_DIRECTORY=$2
			shift 2
			;;
		--nr-directories)
			NUM_DIRECTORIES=$2
			shift 2
			;;
		--iterations)
			NUM_ITERATIONS=$2
			shift 2
			;;
		*)	echo Unrecognised option: $1; shift
	esac
done

# Install if necessary
if [ ! -d $SHELLPACK_SOURCES/fsmark-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-fsmark -v ${VERSION} || die fsmark install script returned error
fi
cd $SHELLPACK_SOURCES/fsmark-${VERSION}-installed || die Failed to cd to fsmark install directory

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

monitor_pre_hook $LOGDIR_RESULTS $SIZE
ln -s $SHELLPACK_TEMP /tmp/fsmark-$$

if [ "$FSMARK_PARALLEL_DIRECTORIES" = "yes" ]; then
	PARAM=
	for THREAD in `seq 1 $NUM_THREADS`; do
		mkdir -p /tmp/fsmark-$$/$THREAD
		PARAM="$PARAM -d /tmp/fsmark-$$/$THREAD"
	done

	./fs_mark \
		$PARAM \
		-D $NUM_DIRECTORIES \
		-N $NUM_FILES_PER_DIRECTORY \
		-n $(($NUM_FILES_PER_ITERATION/$NUM_THREADS)) \
		-L $NUM_ITERATIONS \
		-S0 \
		-s $FILESIZE \
			2>&1 | tee $LOGDIR_RESULTS/fsmark.log \
					|| die Failed to run fsmark
else
	./fs_mark \
		-d /tmp/fsmark-$$ \
		-D $NUM_DIRECTORIES \
		-N $NUM_FILES_PER_DIRECTORY \
		-n $(($NUM_FILES_PER_ITERATION/$NUM_THREADS)) \
		-L $NUM_ITERATIONS \
		-t $NUM_THREADS \
		-S0 \
		-s $FILESIZE \
			2>&1 | tee $LOGDIR_RESULTS/fsmark.log \
					|| die Failed to run fsmark
fi
rm -rf $SHELLPACK_TEMP/*
rm /tmp/fsmark-$$
monitor_post_hook $LOGDIR_RESULTS $SIZE

exit $SHELLPACK_SUCCESS
#### Description fsmark
#### Details fsmark-bench 15
