#!/bin/bash
# This is the script for running the starve benchmark
#
P='starve'
ITERATIONS=15
. $SHELLPACK_INCLUDE/common.sh

# Process the arguments
while [ $# -gt 0 ]; do
	case $1 in
	-i)
		ITERATIONS=$2
		shift 2
		;;
	*)
		echo Unrecognised commane-line parameter $1
		usage
		exit $SHELLPACK_ERROR
	esac
done

# Install support files
if [ ! \( -e $SHELLPACK_SOURCES/starve/test-starve \) ]; then
  	$SHELLPACK_INCLUDE/shellpack-install-starve
	check_status "$P: Installing starve"
fi


pushd $SHELLPACK_SOURCES/starve > /dev/null

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

# Run the test and gather results
for i in `seq 1 $ITERATIONS`; do
	echo Pass $i

	$TIME_CMD ./test-starve 2>> $LOGDIR_RESULTS/time.$i > /dev/null
	grep elapsed $LOGDIR_RESULTS/time.$i
done
cat $LOGDIR_RESULTS/time.* | grep elapsed > $LOGDIR_RESULTS/time

exit $RETVAL
#### Description Run the scheduler starve benchmark
#### Details starve-bench 3
