#!/bin/bash
P=stockfish-install
DEFAULT_VERSION=0
. $SHELLPACK_INCLUDE/common.sh
GIT_LOCATION=https://github.com/mcostalba/Stockfish.git
MIRROR_LOCATION="$WEBROOT/stockfish/"

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

# Unconditionally fetch the tar to find out the real version number
TARFILE=stockfish-${VERSION}.tar.gz
git_fetch $GIT_LOCATION stockfish-${VERSION} $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
        error "$P: tar xf stockfish-${VERSION}.tar.gz failed"
        popd > /dev/null
        exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR stockfish-${VERSION}
pushd stockfish-${VERSION} > /dev/null || die Failed to rename tar

pushd $SHELLPACK_SOURCES/stockfish-${VERSION}/src || die Failed to change to source directory
git checkout 54f8a9cb138a1bc0b0054b98f911fafd8d1b03ad
ARCH=`uname -m | sed -e 's/_/-/'`
make build ARCH=$ARCH PREFIX=$SHELLPACK_SOURCES/stockfish-${VERSION}-installed || die Failed to run make build
make install ARCH=$ARCH PREFIX=$SHELLPACK_SOURCES/stockfish-${VERSION}-installed || die Failed to run make install

echo stockfish installed successfully
#### Description stockfish
#### Details stockfish 7
