#!/bin/bash
# This script installs libreoffice and builds it
P=libreofficebuild-bench
VERSION=20110725
NUMCPUS=$(grep -c '^processor' /proc/cpuinfo)
. $SHELLPACK_INCLUDE/common.sh

# Basic args parser
while [ "$1" != "" ]; do
	case "$1" in
		-v)
			VERSION=$2
			shift 2;;
		*)	echo Unrecognised option: $1; shift
	esac
done

# Install if necessary
if [ ! -d $SHELLPACK_SOURCES/libreofficebuild-${VERSION}-source ]; then
	$SHELLPACK_INCLUDE/shellpack-install-libreofficebuild -v ${VERSION} || die libreofficebuild install script returned error
fi
cd $SHELLPACK_SOURCES/libreofficebuild-${VERSION}-source || die Failed to cd to libreoffice build directory

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

./autogen.sh --with-num-cpus=$NUMCPUS --with-max-jobs=$((NUMCPUS*4)) || die Failed to run autogen
make || die Failed to build libreoffice

make clean

exit $SHELLPACK_SUCCESS
#### Description Build libreoffice
#### Details libreofficebuild-bench 3
