#!/bin/bash
# phpbench installer
P=siege-install
DEFAULT_VERSION=0.8.1
. $SHELLPACK_INCLUDE/common.sh
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

WEB_LOCATION=https://download.pureftpd.org/pub/phpbench
MIRROR_LOCATION="$WEBROOT/phpbench/"
APACHE_VERSION=2.4.17
APR_VERSION=1.5.2
PCRE_VERSION=8.35

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=
SERVERSIDE_COMMAND=none
SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--serverside-command)
		SERVERSIDE_COMMAND=$2
		shift 2
		;;
	--serverside-name)
		SERVERSIDE_NAME=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/apache-build-${APACHE_VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/apache-build-${APACHE_VERSION}-installed ]; then
	mmtests_activity source-install
	$SHELLPACK_INCLUDE/shellpack-install-apachebuild -v ${APACHE_VERSION}  || die apachebuild install script returned error
	mmtests_activity source-installed
fi
cd $SHELLPACK_SOURCES/apachebuild-${APACHE_VERSION}-installed || die Failed to cd to apachebuild install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo apachebuild installed only as requested.
	exit $SHELLPACK_SUCCESS
fi
# Unconditionally fetch the tar to find out the real version number
TARFILE=phpbench-${VERSION}.tar.gz
sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
	error "$P: tar xf phpbench-${VERSION}.tar.gz failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR phpbench-${VERSION}-installed
pushd phpbench-${VERSION}-installed > /dev/null || die Failed to rename tar

echo phpbench successfully
exit $SHELLPACK_SUCCESS
#### Description phpbench
#### Details phpbench 12
