#!/bin/bash

P='vmr-aim9-install'
WEB_LOCATION="http://heanet.dl.sourceforge.net/sourceforge/aimbench/s9110.tar.Z"
MIRROR_LOCATION="$WEBROOT/aim9/s9110.tar.Z"

. $SHELLPACK_INCLUDE/common.sh

cd $SHELLPACK_SOURCES || die Sources directory does not exist
rm -rf aim9

sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/s9110.tar.Z
tar zxf s9110.tar.Z || die Failed to untar
cd aim9 || die aim9 directory does not exist after untar

echo  > aim9.configure
echo >> aim9.configure
echo >> aim9.configure
echo >> aim9.configure
echo >> aim9.configure

cat aim9.configure | ./S9setup || die Failed to configure aim9
make || die Failed to make aim9

cp s9workfile s9workfile-full
echo "# @(#) s9workfile:1.2 1/22/96 00:00:00
# AIM Independent Resource Benchmark - Suite IX Workfile
FILESIZE: 5M >> s9workfile-short
creat-clo
page_test
brk_test
jmp_test
signal_test
exec_test
fork_test
link_test" >> s9workfile-short

exit $SHELLPACK_SUCCESS
#### Description Run the VMRegress based aim9 benchmark
#### Details vmr-aim9 8
