#!/bin/bash
P=linkbench-install
DEFAULT_VERSION=0
. $SHELLPACK_INCLUDE/common.sh
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi
GIT_LOCATION=https://github.com/davidlohr/linkbench
#MIRROR_LOCATION="$WEBROOT/linkbench/"

VERSION=0
MAVEN_VERSION=3.3.9
FIRST_DB_INSTALL=false
MARIADB_VERSION=10.2.14
MARIADB_DBNAME=linkdb
MARIADB_ADMIN_USER=root
MARIADB_ADMIN_PASSWORD=mmtests-default
MYSQLCMD="${SHELLPACK_SOURCES}/mariadbbuild-${MARIADB_VERSION}-installed/bin/mysql -u $MARIADB_ADMIN_USER -p$MARIADB_ADMIN_PASSWORD"
MYSQLADMIN="${SHELLPACK_SOURCES}/mariadbbuild-${MARIADB_VERSION}-installed/bin/mysqladmin -u $MARIADB_ADMIN_USER -p$MARIADB_ADMIN_PASSWORD"

CONFIG_PATH=$SHELLPACK_SOURCES/linkbench-$VERSION-installed/config
FACEBOOK_CONF=$CONFIG_PATH/FBWorkload.properties

# Only updates the first occurance of the parameter
update_entry_cnf() {
	PARAMETER=$1
	VALUE=$2

	LINE=`grep -n "^$PARAMETER" $FACEBOOK_CONF | cut -d: -f1 | head -1`
	if [ "$LINE" = "" ]; then
		LINE=`grep -n "^#$PARAMETER" $FACEBOOK_CONF | cut -d: -f1 | head -1`
		if [ "$LINE" = "" ]; then
			die Failed to locate parameter $PARAMETER
		fi
	fi
	LINEC=`wc -l $FACEBOOK_CONF | awk '{print $1}'`
	head -$(($LINE-1)) $FACEBOOK_CONF > ${FACEBOOK_CONF}.tmp
	echo $PARAMETER = $VALUE >> ${FACEBOOK_CONF}.tmp
	tail -$(($LINEC-$LINE)) $FACEBOOK_CONF >> ${FACEBOOK_CONF}.tmp

	mv ${FACEBOOK_CONF}.tmp $FACEBOOK_CONF
}

# PART 1: Check/install dependencies:
install-depends java-1_7_0-openjdk java-1_7_0-openjdk-devel

if [ ! -e $SHELLPACK_SOURCES/maven-build-${MAVEN_VERSION}-installed ]; then
	echo Installing Apache Maven
	$SHELLPACK_INCLUDE/shellpack-install-mavenbuild -v ${MAVEN_VERSION} || die Failed to install Apache Maven
	echo Apache Maven successfully installed.
fi

# Now install mariadb/mysql
if [ ! -e $SHELLPACK_SOURCES/mariadb-build-${MARIADB_VERSION}-installed ]; then
	echo Installing mariadb server
	FIRST_DB_INSTALL=true
	$SHELLPACK_INCLUDE/shellpack-install-mariadbbuild -v ${MARIADB_VERSION} || die Failed to install mariadb
	echo MariaDB server successfully installed.
fi

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=
SERVERSIDE_COMMAND=none
SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--serverside-command)
		SERVERSIDE_COMMAND=$2
		shift 2
		;;
	--serverside-name)
		SERVERSIDE_NAME=$2
		shift 2
		;;
	--workload-size)
		LINKBENCH_WORKLOAD_SIZE=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ ! -e $JAVA_HOME ]; then
	install-depends java-1_7_0-openjdk
	install-depends java-1_7_0-openjdk-devel

	if [ ! -e /usr/lib64/jvm/java ]; then
		echo ERROR: Java binary is not located at $JAVA_HOME as configured
		exit -1
	fi
	export JAVA_HOME=/usr/lib64/jvm
fi
export PATH=$JAVA_HOME:$JAVA_HOME/bin:$PATH

# Unconditionally fetch the tar to find out the real version number
TARFILE=linkbench-${VERSION}.tar.gz
git_fetch $GIT_LOCATION linkbench-${VERSION}-installed $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
	error "$P: tar xf linkbench-${VERSION}.tar.gz failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR linkbench-${VERSION}-installed
pushd linkbench-${VERSION}-installed > /dev/null || die Failed to rename tar
MAVENCMD=$SHELLPACK_SOURCES/mavenbuild-${MAVEN_VERSION}-installed/bin/mvn
$MAVENCMD clean package -DskipTests

# this influences innodb_buffer_pool_instances, but
# let's mariadb handle that automatically (ie by 128MB chunks),
# so just change the pool size -- iff MEMTOTAL_BYTES/2 > 1Gb
# of course.
BUFF_POOL_SIZE=$(($MEMTOTAL_BYTES/2))

DBSTART_OPTIONS="--innodb_flush_method=nosync,--innodb_flush_log_at_trx_commit=0,--innodb_buffer_pool_size=${BUFF_POOL_SIZE},--innodb_log_file_size=512M,--max_allowed_packet=1G"

$SHELLPACK_INCLUDE/shellpack-bench-mariadbbuild --start \
	--start_opts $DBSTART_OPTIONS \
	--effective_cachesize $((MEMTOTAL_BYTES*6/10)) \
	--shared_buffers $((MEMTOTAL_BYTES/4)) \
	--work_mem $((16*1048576)) || die Failed to get usable database installation

$MYSQLCMD -e "CREATE DATABASE IF NOT EXISTS ${MARIADB_DBNAME}"
$MYSQLCMD $MARIADB_DBNAME < $SHELLPACK_SOURCES/linkbench-${VERSION}-installed/scripts/linkdb-install.sql 2>&1 | tee $LOGDIR_RESULTS/linkdb-install.log

# Setup linkbench configurations
cp $CONFIG_PATH/LinkConfigMysql.properties $CONFIG_PATH/MyConfig.properties

# Update the default DB size (nodeids ~= 1Kb)
update_entry_cnf maxid1 $((LINKBENCH_WORKLOAD_SIZE/1000))

# This is the data-load phase (disable binary logging, faster loading ).
$MYSQLCMD $MARIADB_DBNAME < $SHELLPACK_SOURCES/linkbench-${VERSION}-installed/scripts/pre-load.sql

$SHELLPACK_SOURCES/linkbench-${VERSION}-installed/bin/linkbench -c $CONFIG_PATH/MyConfig.properties \
    -L $LOGDIR_RESULTS/linkbench-load.log \
    -D loaders=$LINKBENCH_MAX_THREADS -l

$MYSQLCMD $MARIADB_DBNAME < $SHELLPACK_SOURCES/linkbench-${VERSION}-installed/scripts/post-load.sql

$SHELLPACK_INCLUDE/shellpack-bench-mariadbbuild --stop

echo linkbench installed successfully
#### Description linkbench
#### Details linkbench 7
