#!/bin/bash
# This script installs fsmark and runs the regression tests

P=fsmark-bench
DEFAULT_VERSION=3.3
. $SHELLPACK_INCLUDE/common.sh
NUM_THREADS=1
NUMCPUS_THREADS=1
NUM_DIRECTORIES=100
NUM_FILES_PER_DIRECTORY=25000
NUM_FILES_PER_ITERATION=50000
NUM_ITERATIONS=63
FILESIZE=0
CPU_FACTOR=1

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	--threads)
		NUM_THREADS=$2
		shift 2
		;;
	--filesize)
		FILESIZE=$2
		shift 2
		;;
	--nr-files-per-iteration)
		NUM_FILES_PER_ITERATION=$2
		shift 2
		;;
	--nr-files-per-directory)
		NUM_FILES_PER_DIRECTORY=$2
		shift 2
		;;
	--nr-directories)
		NUM_DIRECTORIES=$2
		shift 2
		;;
	--iterations)
		NUM_ITERATIONS=$2
		shift 2
		;;
	--threads-per-cpu)
		NUMCPUS_THREADS=$2
		NUM_THREADS=$(($NUMCPUS_THREADS*$NUMCPUS))
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/fsmark-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/fsmark-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-fsmark -v ${VERSION}  || die fsmark install script returned error
fi
cd $SHELLPACK_SOURCES/fsmark-${VERSION}-installed || die Failed to cd to fsmark install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo fsmark installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

monitor_pre_hook $LOGDIR_RESULTS $SIZE
ln -s $TESTDISK_DIR /tmp/fsmark-$$

if [ "$FSMARK_PARALLEL_DIRECTORIES" = "yes" ]; then
	PARAM=
	for THREAD in `seq 1 $NUM_THREADS`; do
		mkdir -p /tmp/fsmark-$$/$THREAD
		PARAM="$PARAM -d /tmp/fsmark-$$/$THREAD"
	done

	./fs_mark \
		$PARAM \
		-D $NUM_DIRECTORIES \
		-N $NUM_FILES_PER_DIRECTORY \
		-n $(($NUM_FILES_PER_ITERATION/$NUM_THREADS)) \
		-L $NUM_ITERATIONS \
		-S0 \
		-s $FILESIZE \
			2>&1 | tee $LOGDIR_RESULTS/fsmark.log \
					|| die Failed to run fsmark
else
	./fs_mark \
		-d /tmp/fsmark-$$ \
		-D $NUM_DIRECTORIES \
		-N $NUM_FILES_PER_DIRECTORY \
		-n $(($NUM_FILES_PER_ITERATION/$NUM_THREADS)) \
		-L $NUM_ITERATIONS \
		-t $NUM_THREADS \
		-S0 \
		-s $FILESIZE \
			2>&1 | tee $LOGDIR_RESULTS/fsmark.log \
					|| die Failed to run fsmark
fi
rm -rf $TESTDISK_DIR/*
rm /tmp/fsmark-$$
monitor_post_hook $LOGDIR_RESULTS $SIZE

exit $SHELLPACK_SUCCESS
#### Description fsmark
#### Details fsmark-bench 23
