#!/bin/bash

P=aim9-install
DEFAULT_VERSION=1.03a
. $SHELLPACK_INCLUDE/common.sh
WEB_LOCATION="http://heanet.dl.sourceforge.net/sourceforge/aimbench"
WEB_LOCATION="http://switch.dl.sourceforge.net/project/bonnie/Bonnie%2B%2B/"
MIRROR_LOCATION="$WEBROOT/bonnie"

# Basic argument parser
while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

rm -rf $SHELLPACK_SOURCES/bonnie-${VERSION}
# Unconditionally fetch the tar to find out the real version number
TARFILE=bonnie%2B%2B-${VERSION}.tgz
sources_fetch $WEB_LOCATION/${VERSION}/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
        error "$P: tar xf bonnie%2B%2B-${VERSION}.tgz failed"
        popd > /dev/null
        exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR bonnie-$VERSION
pushd bonnie-$VERSION > /dev/null || die Failed to rename tar

pushd $SHELLPACK_SOURCES/bonnie-$VERSION || die Failed to change to source directory
echo "diff --git a/zcav.cpp b/zcav.cpp
index c08994e..fa278e0 100644
--- a/zcav.cpp
+++ b/zcav.cpp
@@ -9,6 +9,7 @@ using namespace std;
 #include <sys/stat.h>
 #include <fcntl.h>
 #include <stdlib.h>
+#include <string.h>
 #include \"bonnie.h\"
 #ifdef HAVE_VECTOR
 #include <vector>" | patch -p1 || exit $SHELLPACK_ERROR
./configure --prefix=$SHELLPACK_SOURCES/bonnie-${VERSION}-installed
if [ $? -ne 0 ]; then
	error "$P: configure failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
make -j$NUMCPUS
if [ $? -ne 0 ]; then
	error "$P: make failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
make install
if [ $? -ne 0 ]; then
	error "$P: make install failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi

exit $SHELLPACK_SUCCESS
#### Description bonnie
#### Details bonnie 22
