#!/bin/bash
# Run dedup benchmark

P=dedup-bench
DEFAULT_VERSION=0
. $SHELLPACK_INCLUDE/common.sh
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

ITERATIONS=12
TESTLIST=

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	--min-threads)
		DEDUP_MIN_THREADS=$2
		shift 2
		;;
	--max-threads)
		DEDUP_MAX_THREADS=$2
		shift 2
		;;
	--iterations)
		DEDUP_ITERATIONS=$2
		shift 2
		;;
	--file)
		DEDUP_FILE=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/dedup-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/dedup-${VERSION}-installed ]; then
	mmtests_activity source-install
	$SHELLPACK_INCLUDE/shellpack-install-dedup -v ${VERSION}  || die dedup install script returned error
	mmtests_activity source-installed
fi
cd $SHELLPACK_SOURCES/dedup-${VERSION}-installed || die Failed to cd to dedup install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo dedup installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

THREADS=
START_THREAD=$DEDUP_MIN_THREADS
END_THREAD=$DEDUP_MAX_THREADS
if [ $END_THREAD -gt 32 ]; then
	THREADS=`seq $START_THREAD 3 8`
	THREADS="$THREADS `seq 12 9 32`"
	THREADS="$THREADS `seq 48 31 $END_THREAD`"
elif [ $END_THREAD -gt 8 ]; then
	THREADS=`seq $START_THREAD 2 8`
	THREADS="$THREADS `seq 12 6 $END_THREAD`"
else
	THREADS=`seq $START_THREAD 2 $END_THREAD`
fi
if [ `echo $THREADS | awk '{print $NF}'` -ne $END_THREAD ]; then
	THREADS="$THREADS $END_THREAD"
fi

for NR_THREADS in $THREADS; do
	mmtests_activity process $NR_THREADS/$END_THREAD
	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
for ITERATION in `seq 1 $DEDUP_ITERATIONS`; do
	mmtests_activity iteration $ITERATION
		echo Starting threads $NR_THREADS/$DEDUP_MAX_THREADS iteration $ITERATION/$DEDUP_ITERATIONS
		$TIME_CMD -o $LOGDIR_RESULTS/dedup-${NR_THREADS}-$ITERATION.time \
		    ./dedup -v -c -p -t $NR_THREADS -i $DEDUP_FILE -o $SHELLPACK_TEMP/tmp.file 2>&1 \
		    tee $LOGDIR_RESULTS/dedup-${NR_THREADS}-${ITERATION}.log || die Failed to run dedup
		rm $SHELLPACK_TEMP/tmp.file #cleanup

done
	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
done
exit $SHELLPACK_SUCCESS
#### Description dedup
#### Details dedup-bench 7
