#!/bin/bash
# This script installs pft and whatever
P=pft-bench
DEFAULT_VERSION=0.12x
. $SHELLPACK_INCLUDE/common.sh

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/pft-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/pft-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-pft -v ${VERSION}  || die pft install script returned error
fi
cd $SHELLPACK_SOURCES/pft-${VERSION}-installed || die Failed to cd to pft install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo pft installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

PFT_CLIENT_SWITCH=-t
if [ "$PFT_USE_PROCESSES" = "yes" ]; then
	PFT_CLIENT_SWITCH=-n
fi

cd $SHELLPACK_SOURCES/pft-${VERSION}-installed || die Failed to cd to pft directory
CLIENT=1
while [ $CLIENT -le $PFT_MAX_CLIENTS ]; do
	monitor_pre_hook $LOGDIR_RESULTS $CLIENT
	echo -n > $LOGDIR_RESULTS/pft-$CLIENT.log
	for ITER in `seq 1 $PFT_ITERATIONS`; do
		( ./pft \
			-m			$PFT_MAPPING_SIZE \
			$PFT_CLIENT_SWITCH	$CLIENT		  \
			2>&1 | tee -a $LOGDIR_RESULTS/pft-$CLIENT.log ) \
				|| die Failed to run pft
	done
	monitor_post_hook $LOGDIR_RESULTS $CLIENT
	CLIENT=$((CLIENT+1))
done

exit $SHELLPACK_SUCCESS
#### Description pft
#### Details pft-bench 9
