#!/bin/bash

P=ebizzy-install
DEFAULT_VERSION=0.3
. $SHELLPACK_INCLUDE/common.sh
WEB_LOCATION="http://heanet.dl.sourceforge.net/sourceforge/ebizzy"
MIRROR_LOCATION="$WEBROOT/ebizzy"

# Basic argument parser
while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

# Unconditionally fetch the tar to find out the real version number
TARFILE=ebizzy-${VERSION}.tar.gz
sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
        error "$P: tar xf ebizzy-${VERSION}.tar.gz failed"
        popd > /dev/null
        exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR ebizzy-$VERSION
pushd ebizzy-$VERSION > /dev/null || die Failed to rename tar

pushd $SHELLPACK_SOURCES/ebizzy-$VERSION || die Failed to change to source directory
./configure --prefix=$SHELLPACK_SOURCES/-installed
if [ $? -ne 0 ]; then
	error "$P: configure failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
make -j$NUMCPUS
if [ $? -ne 0 ]; then
	error "$P: make failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
mkdir -p ../ebizzy-$VERSION-installed/bin
cp ebizzy ../ebizzy-$VERSION-installed/bin || exit $SHELLPACK_ERROR

exit $SHELLPACK_SUCCESS
#### Description ebizzy
#### Details ebizzy 5
