#!/bin/bash
# This script installs netperf and runs the regression tests
P=netperf-bench
DEFAULT_VERSION=2.4.5
. $SHELLPACK_INCLUDE/common.sh
NUMCPUS=`grep processor /proc/cpuinfo | wc -l`
PROTOCOLS="UDP_STREAM TCP_STREAM"
BUFFER_SIZES="64 128 256 1024 2048 3312 4096 6144 8192 10240 12288 14336 16384"

TASKSET_SERVER=
TASKSET_CLIENT=

# Basic argument parser
while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	--udp-only)
		PROTOCOLS=UDP_STREAM
		shift
		;;
	--tcp-only)
		PROTOCOLS=TCP_STREAM
		shift
		;;
	--bind-same)
		TASKSET_SERVER="taskset -c 0"
		TASKSET_CLIENT="taskset -c 0"
		shift
		;;
	--bind-firstsecond)
		TASKSET_SERVER="taskset -c 0"
		TASKSET_CLIENT="taskset -c 1"
		shift
		;;
	--bind-firstlast)
		TASKSET_SERVER="taskset -c 0"
		TASKSET_CLIENT="taskset -c $(($NUMCPUS-1))"
		shift
		;;
	--buffer-sizes)
		BUFFER_SIZES=`echo $2 | tr ',' ' '`
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/netperf-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/netperf-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-netperf -v ${VERSION}  || die netperf install script returned error
fi
cd $SHELLPACK_SOURCES/netperf-${VERSION}-installed || die Failed to cd to netperf install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo netperf installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

cd $SHELLPACK_SOURCES/netperf-${VERSION}-installed || die Failed to cd to netperf directory

echo Killing old servers
killall netserver

echo Starting server
NETROOT=$SHELLPACK_SOURCES/netperf-${VERSION}-installed 
$TASKSET_SERVER $NETROOT/bin/netserver || die Failed to start netserver
sleep 2

for PROTOCOL in $PROTOCOLS; do
	echo -n > $LOGDIR_RESULTS/netperf-$PROTOCOL.result

	EXTRA=
	if [ "$PROTOCOL" = "UDP_STREAM" ]; then
		EXTRA="-P 15895 -s 32768 -S 32768"
	fi
	
	for SIZE in $BUFFER_SIZES; do
		echo Running test $PROTOCOL 
		monitor_pre_hook $LOGDIR_RESULTS $SIZE
		$TASKSET_CLIENT $NETROOT/bin/netperf \
			-t $PROTOCOL \
			-i 30,6 -I 99,1 \
			-l 20 \
			-H 127.0.0.1 \
			-- \
			$EXTRA \
			-m $SIZE \
			-M $SIZE \
				2>&1 | tee $LOGDIR_RESULTS/$PROTOCOL-$SIZE.log \
				|| die Failed to run netperf
		monitor_post_hook $LOGDIR_RESULTS $SIZE
		if [ "$PROTOCOL" = "UDP_STREAM" ]; then
			echo -n "$SIZE " >> $LOGDIR_RESULTS/netperf-$PROTOCOL.result
			grep -v '[a-zA-Z]' $LOGDIR_RESULTS/$PROTOCOL-$SIZE.log | grep -v '^$' | tail -1 | awk '{print $4}' >> $LOGDIR_RESULTS/netperf-$PROTOCOL.result
		else
			grep -v '[a-zA-Z]' $LOGDIR_RESULTS/$PROTOCOL-$SIZE.log | grep -v '^$' | head -1 | awk '{print $3" "$5}' >> $LOGDIR_RESULTS/netperf-$PROTOCOL.result
		fi
	done
done
killall netserver

exit $SHELLPACK_SUCCESS
#### Description Netperf benchmark
#### Details netperf-bench 14
