#!/bin/bash

P='specjvm-install'
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/spec/SPECjvm2008_1_00_setup.jar"
export PATH=$SPECJVM_JRE:$PATH

. $SHELLPACK_INCLUDE/common.sh

cd $SHELLPACK_SOURCES || die Sources directory does not exist

sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/SPECjvm2008_1_00_setup.jar
cd $SHELLPACK_SOURCES
java -jar SPECjvm2008_1_00_setup.jar -DUSER_INSTALL_DIR=`pwd`/specjvm -i silent || die Failed to install specjvm

exit $SHELLPACK_SUCCESS
#### Description SPECjvm
#### Details specjvm 13
