#!/bin/bash
# This script installs the page fault test
P=pft-install
VERSION=0.12x
. $SHELLPACK_INCLUDE/common.sh

# Basic args parser
while [ "$1" != "" ]; do
	case "$1" in
		-v)
			VERSION=$2
			shift 2;;
		*)	echo Unrecognised option: $1; shift
	esac
done

# Download PFT
TARFILE=pft-${VERSION}.tar.gz
WEB_LOCATION="http://free.linux.hp.com/~lts/Tools"
MIRROR_LOCATION="$WEBROOT/pft/$TARFILE"
sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
pushd $SHELLPACK_SOURCES > /dev/null

# Uncompress it
tar xf pft-${VERSION}.tar.gz
if [ $? -ne 0 ]; then
	error "$P: tar xf pft-${VERSION}.tar.gz failed"
	exit $SHELLPACK_ERROR
fi

# Rename it
DST_DIR=`tar ztf pft-${VERSION}.tar.gz | head -n 1`
mv $DST_DIR pft-$VERSION-installed

# Build it
pushd $SHELLPACK_SOURCES/pft-${VERSION}-installed
make
if [ $? -ne 0 ]; then
	error "$P: make failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi

echo pft installed successfully
#### Description pft
#### Details pft 3
