#!/bin/bash
P=trinity-install
DEFAULT_VERSION=0
. $SHELLPACK_INCLUDE/common.sh
GIT_LOCATION=https://github.com/kernelslacker/trinity
MIRROR_LOCATION="$WEBROOT/trinity/"

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

# Unconditionally fetch the tar to find out the real version number
TARFILE=trinity-${VERSION}.tar.gz
git_fetch $GIT_LOCATION trinity-${VERSION}-installed $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
        error "$P: tar xf trinity-${VERSION}.tar.gz failed"
        popd > /dev/null
        exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR trinity-${VERSION}-installed
pushd trinity-${VERSION}-installed > /dev/null || die Failed to rename tar

pushd $SHELLPACK_SOURCES/trinity-${VERSION}-installed || die Failed to change to source directory
git checkout $VERSION
./configure.sh || die Failed to run configure.sh
make -j$NUMCPUS 
if [ $? -ne 0 ]; then
	error "$P: make failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
chmod a+w .

echo trinity installed successfully
#### Description trinity fuzzing tool
#### Details trinity 6
