#!/bin/bash
# Perl Compatible RE installer for Apache httpd
P=pcrebuild-install
DEFAULT_VERSION=8.35
. $SHELLPACK_INCLUDE/common.sh

WEB_LOCATION=ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre
MIRROR_LOCATION="$WEBROOT/apache/"

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

# PCRE, use pcre naming to limit extra junk
# Unconditionally fetch the tar to find out the real version number
TARFILE=pcre-${VERSION}.tar.bz2
sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
        error "$P: tar xf pcre-${VERSION}.tar.bz2 failed"
        popd > /dev/null
        exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR pcrebuild-${VERSION}
pushd pcrebuild-${VERSION} > /dev/null || die Failed to rename tar
pushd $SHELLPACK_SOURCES/pcrebuild-${VERSION} || die Failed to change to source directory
export CFLAGS="-O2 $CFLAGS_MMTESTS_EXTRA"
eval ./configure --prefix=$SHELLPACK_SOURCES/pcrebuild-${VERSION}-installed 
if [ $? -ne 0 ]; then
	error "$P: configure failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
unset CFLAGS
make -j$NUMCPUS 
if [ $? -ne 0 ]; then
	error "$P: make failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi
make install
if [ $? -ne 0 ]; then
	error "$P: make install failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi

echo pcrebuild installed successfully
#### Description pcrebuild
#### Details pcrebuild 7
