#!/bin/bash
P=libmicro-bench
DEFAULT_VERSION=1
. $SHELLPACK_INCLUDE/common.sh

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/libmicro-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/libmicro-${VERSION}-installed ]; then
	$SHELLPACK_INCLUDE/shellpack-install-libmicro -v ${VERSION}  || die libmicro install script returned error
fi
cd $SHELLPACK_SOURCES/libmicro-${VERSION}-installed || die Failed to cd to libmicro install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo libmicro installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

cd $SHELLPACK_SOURCES/libmicro-${VERSION}-installed || die Failed to cd to libmicro directory

COMMON="-E -C 200 -L -S -W"

while read A B C; do
	monitor_pre_hook $LOGDIR_RESULTS $B
	if [ -f bin/$A ]; then
		eval bin/$A $COMMON -N "$B" $C 2>&1 > $LOGDIR_RESULTS/$B.log
	fi
	monitor_post_hook $LOGDIR_RESULTS $B
done <<EOT
memset	memset_10	-s 10  -I 10 
memset	memset_256	-s 256 -I 20
memset	memset_256_u	-s 256 -I 20  -a 1
memset	memset_1k	-s 1k  -I 100
memset	memset_4k	-s 4k  -I 250
memset	memset_4k_uc	-s 4k  -I 400 -u
memset	memset_10k	-s 10k -I 600   
memset	memset_1m	-s 1m  -I 200000
memset	memset_10m	-s 10m -I 2000000 
memset	memsetP2_10m	-s 10m -I 2000000 -P 2
EOT

exit $SHELLPACK_SUCCESS
#### Description libmicro
#### Details libmicro-bench 7
