#!/bin/bash
P=libmicro-socket-bench
DEFAULT_VERSION=1
. $SHELLPACK_INCLUDE/common.sh
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

# Basic argument parser
TASKSET_SERVER=
TASKSET_CLIENT=
SERVERSIDE_COMMAND=none
SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`

while [ "$1" != "" ]; do
	case "$1" in
	-v)
		VERSION=$2
		shift 2
		;;
	--serverside-command)
		SERVERSIDE_COMMAND=$2
		shift 2
		;;
	--serverside-name)
		SERVERSIDE_NAME=$2
		shift 2
		;;
	--install-only)
		INSTALL_ONLY=yes
		shift
		;;
	--install-force)
		INSTALL_FORCE=yes
		shift
		;;
	*)
		echo Unrecognised option: $1
		shift
	esac
done
if [ "$TASKSET_SERVER" != "" ]; then
	echo TASKSET_SERVER: $TASKSET_SERVER
	echo TASKSET_CLIENT: $TASKSET_CLIENT
fi
if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

if [ "$INSTALL_FORCE" = "yes" ]; then
	rm -rf $SHELLPACK_SOURCES/libmicro-socket-${VERSION}
fi
if [ ! -d $SHELLPACK_SOURCES/libmicro-socket-${VERSION}-installed ]; then
	mmtests_activity source-install
	$SHELLPACK_INCLUDE/shellpack-install-libmicro-socket -v ${VERSION}  || die libmicro-socket install script returned error
	mmtests_activity source-installed
fi
cd $SHELLPACK_SOURCES/libmicro-socket-${VERSION}-installed || die Failed to cd to libmicro-socket install directory
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo libmicro-socket installed only as requested.
	exit $SHELLPACK_SUCCESS
fi

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

cd $SHELLPACK_SOURCES/libmicro-socket-${VERSION}-installed || die Failed to cd to libmicro directory

COMMON="-E -C 2000 -L -S -W"

while read A B C; do
	monitor_pre_hook $LOGDIR_RESULTS $B
	if [ -f bin/$A ]; then
		eval bin/$A $COMMON -N "$B" $C 2>&1 > $LOGDIR_RESULTS/$B.log
	fi
	monitor_post_hook $LOGDIR_RESULTS $B
done <<EOT
getsockname	getsockname	-B 10000
getpeername	getpeername	-B 10000
socket	socket_u	-B 10000
socket	socket_i	-B 10000	-f PF_INET
socketpair	socketpair	-B 10000
setsockopt	setsockopt	-B 10000
bind	bind	-B 10000
listen	listen	-B 10000
poll	poll_10	-n 10	-B 10000
poll	poll_100	-n 100	-B 10000
poll	poll_1000	-n 1000	-B 10000
poll	poll_w10	-n 10	-B 10000	-w 1
poll	poll_w100	-n 100	-B 10000	-w 10
poll	poll_w1000	-n 1000	-B 10000	-w 100
select	select_10	-n 10	-B 10000
select	select_100	-n 100	-B 10000
select	select_1000	-n 1000	-B 10000
select	select_w10	-n 10	-B 10000	-w 1
select	select_w100	-n 100	-B 10000	-w 10
select	select_w1000	-n 1000	-B 10000 -w 100
connection	connection	-B 10000
connection	conn_accept	-B 10000 -a
connection	conn_connect	-B 10000 -c
close_tcp	close_tcp	-B 10000
EOT

exit $SHELLPACK_SUCCESS
#### Description libmicro-socket
#### Details libmicro-socket-bench 4
