#!/bin/bash

P='hackbench-install'
WEB_LOCATION="http://people.redhat.com/mingo/cfs-scheduler/tools/hackbench.c"
MIRROR_LOCATION="$WEBROOT/hackbench/hackbench.c"

. $SHELLPACK_INCLUDE/common.sh

cd $SHELLPACK_SOURCES || die Sources directory does not exist
rm -rf hackbench
mkdir -p hackbench

sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/hackbench/hackbench.c
cd $SHELLPACK_SOURCES/hackbench

gcc -O2 -lpthread hackbench.c -o hackbench
if [ $? -ne 0 ]; then
	die "$P: Failed to build hackbench"
fi

exit $SHELLPACK_SUCCESS
#### Description Run the HackBench benchmark
#### Details hackbench 11
