#!/bin/bash
# libreofficebuild installer
P=libreofficebuild-install
GIT_LOCATION=git://anongit.freedesktop.org/libreoffice/bootstrap
MIRROR_LOCATION="$WEBROOT/libreoffice/"
DEFAULT_VERSION=20110725
. $SHELLPACK_INCLUDE/common.sh

# Basic argument parser
while [ "$1" != "" ]; do
  case "$1" in
    -v)
            VERSION=$2
	    shift 2
	    ;;
    *)
            echo Unrecognised option: $1
	    shift
  esac
done

if [ -z "$VERSION" ]; then
	VERSION=$DEFAULT_VERSION
fi

# Unconditionally fetch the tar to find out the real version number
TARFILE=libreoffice-${VERSION}.tar.gz
git_fetch $GIT_LOCATION libreoffice-$VERSION $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE

cd $SHELLPACK_SOURCES
tar -xf $TARFILE
if [ $? -ne 0 ]; then
	error "$P: tar xf libreoffice-${VERSION}.tar.gz failed"
	popd > /dev/null
	exit $SHELLPACK_ERROR
fi

# Rename directory to something we expect.
DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
mv $DST_DIR libreofficebuild-${VERSION}-source
pushd libreofficebuild-${VERSION}-source > /dev/null || die Failed to rename tar

echo libreoffice source successfully unpacked
#### Description Build libreoffice
#### Details libreofficebuild 3
