#!/bin/bash
# libmicro installer
###SHELLPACK preamble libmicro-install 0.4.2
GIT_LOCATION=https://github.com/gormanm/libMicro
MIRROR_LOCATION="$WEBROOT/libmicro"

install-depends gcc

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch libmicro-${VERSION}.tar.gz libmicro-${VERSION}-installed

###SHELLPACK build_start libmicro-${VERSION}-installed
sed -i -e 's/tattle.c libmicro.a -lrt -lm.*/tattle.c libmicro.a -lrt -lm -lpthread/' Makefile.com

###SHELLPACK make_clean
###SHELLPACK make

echo libmicro installed successfully
