#!/bin/bash
# memtester installer
###SHELLPACK preamble memtester-install 4.3.0
WEB_LOCATION=http://pyropus.ca/software/memtester/old-versions
#memtester-4.3.0.tar.gz
MIRROR_LOCATION="$WEBROOT/memtester/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch memtester-${VERSION}.tar.gz memtester-${VERSION}-installed

# Build
###SHELLPACK build_start memtester-${VERSION}-installed
###SHELLPACK make

echo memtester installed successfully
