#!/bin/bash
# libmicro installer
###SHELLPACK preamble libmicro-memory-install 1
GIT_LOCATION=https://github.com/redhat-performance/libMicro
MIRROR_LOCATION="$WEBROOT/libmicro"

install-depends gcc

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch libmicro-memory-${VERSION}.tar.gz libmicro-memory-${VERSION}-installed

###SHELLPACK build_start libmicro-memory-${VERSION}-installed

###SHELLPACK make_clean
###SHELLPACK make

echo libmicro installed successfully
