#!/bin/bash
###SHELLPACK preamble trinity-install 0
GIT_LOCATION=https://github.com/kernelslacker/trinity
MIRROR_LOCATION="$WEBROOT/extra/trinity/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch trinity-${VERSION}.tar.gz trinity-${VERSION}-installed

###SHELLPACK build_start trinity-${VERSION}-installed
###SHELLPACK build_configure
sed -i -e /syscall_remap_file_pages/d include/syscalls-x86_64.h
###SHELLPACK make
chmod a+w .

echo trinity installed successfully
