#!/bin/bash
###SHELLPACK preamble trinity-install 0
GIT_LOCATION=git://git.codemonkey.org.uk/trinity.git
MIRROR_LOCATION="$WEBROOT/trinity/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch trinity-${VERSION}.tar.gz trinity-${VERSION}-installed

###SHELLPACK build_start trinity-${VERSION}-installed
git checkout $VERSION
./configure.sh || die Failed to run configure.sh
###SHELLPACK make
chmod a+w .

echo trinity installed successfully
