#!/bin/bash
# sysjitter installer
###SHELLPACK preamble sysjitter-install 1.3
WEB_LOCATION=http://www.openonload.org/download/sysjitter
MIRROR_LOCATION="$WEBROOT/sysjitter/"

install-depends popt-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch sysjitter-${VERSION}.tgz sysjitter-${VERSION}-installed

# Build
###SHELLPACK build_start sysjitter-${VERSION}-installed
###SHELLPACK make

echo sysjitter installed successfully
