#!/bin/bash
# sysjitter installer
###SHELLPACK preamble sysjitter-install sysjitter-1.4
GIT_LOCATION="https://github.com/Xilinx-CNS/cns-sysjitter"
MIRROR_LOCATION="$WEBROOT/extra/sysjitter/"

install-depends popt-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch sysjitter-${VERSION}.tgz sysjitter-${VERSION}-installed

# Build
###SHELLPACK make

echo sysjitter installed successfully
exit $SHELLPACK_SUCCESS
