#!/bin/bash
# ffsb installer
###SHELLPACK preamble ffsb-install 6.0-rc2
WEB_LOCATION=http://heanet.dl.sourceforge.net/project/ffsb/ffsb/
MIRROR_LOCATION="$WEBROOT/ffsb/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

WEB_LOCATION=$WEB_LOCATION/$VERSION/ffsb-$VERSION
###SHELLPACK sources_fetch ffsb-${VERSION}.tar.bz2 ffsb-${VERSION}

###SHELLPACK build_start ffsb-${VERSION}
###SHELLPACK build_configure ffsb-${VERSION}
###SHELLPACK make_make_install ffsb-${VERSION}

echo ffsb installed successfully
