#!/bin/bash
###SHELLPACK preamble aom-install v3.3.0
GIT_LOCATION=https://aomedia.googlesource.com/aom
MIRROR_LOCATION="$WEBROOT/extra/aom/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

install-depends cmake git-core nasm yasm p7zip p7zip-full gcc-c++

###SHELLPACK git_fetch aom-${VERSION}.tar.gz aom-${VERSION}
###SHELLPACK build_start_alt aom-${VERSION}
###SHELLPACK build_cmake aom-${VERSION}-build aom-${VERSION} -DENABLE_DOCS=0 -DENABLE_TESTS=0 -DCONFIG_AV1_DECODER=0 -DCMAKE_BUILD_TYPE=Release
###SHELLPACK make_make_install

echo aom installed successfully
exit $SHELLPACK_SUCCESS
