#!/bin/bash
###SHELLPACK preamble mpfrbuild-install 4.0.1

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

WEB_LOCATION="https://www.mpfr.org/mpfr-$VERSION"
MIRROR_LOCATION="$WEBROOT/mpfr/"

###SHELLPACK sources_fetch mpfr-${VERSION}.tar.xz mpfrbuild-${VERSION}
###SHELLPACK build_start mpfrbuild-${VERSION}
###SHELLPACK build_configure mpfrbuild-${VERSION} --with-gmp=$SHELLPACK_SOURCES/gmpbuild-$GMP_VERSION-installed
###SHELLPACK make_make_install
echo mpfr installed successfully
