#!/bin/bash
###SHELLPACK preamble blasbuild v0.3.10
GIT_LOCATION=https://github.com/xianyi/OpenBLAS
MIRROR_LOCATION="$WEBROOT/blasbuild/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch blasbuild-${VERSION}.tar.gz blasbuild-${VERSION}
###SHELLPACK build_start blasbuild-${VERSION}
PREFIX="$SHELLPACK_SOURCES/blasbuild-${VERSION}-installed"
export MAKE_FLAGS="BINARY=64 USE_OPENMP=1 $BLAS_EXTRA_MAKE_FLAGS"
export MAKE_INSTALL_FLAGS="PREFIX=$PREFIX OPENBLAS_LIBRARY_DIR=$PREFIX/$MMTESTS_LIBDIR $MAKE_FLAGS"
###SHELLPACK make_make_install

echo blasbuild installed successfully
