#!/bin/bash
###SHELLPACK preamble blasbuild v0.3.30
GIT_LOCATION=https://github.com/xianyi/OpenBLAS
MIRROR_LOCATION="$WEBROOT/blasbuild/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch blasbuild-${VERSION}.tar.gz blasbuild-${VERSION}
###SHELLPACK build_start blasbuild-${VERSION}
PREFIX="$SHELLPACK_SOURCES/blasbuild-${VERSION}-installed"
export MAKE_FLAGS="BINARY=64 USE_OPENMP=1 $BLAS_EXTRA_MAKE_FLAGS"
export MAKE_INSTALL_FLAGS="PREFIX=$PREFIX OPENBLAS_LIBRARY_DIR=$PREFIX/$MMTESTS_LIBDIR $MAKE_FLAGS"

# Try workaround potential for IceLake not being detected
# This is not reliable as the target CPU may also not be
# skylake
make -j$NUMCPUS
if [ $? -ne 0 -a "`uname -m`" = "x86_64" ]; then
	export MAKE_FLAGS="$MAKE_FLAGS TARGET=SKYLAKEX"
fi

###SHELLPACK make
###SHELLPACK make_install

echo blasbuild installed successfully
