#!/bin/bash
###SHELLPACK preamble blasbuild-bench blas-v0.3.30

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargBindings
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

export BLAS_VERSION="v0.3.30"
# dependencies
###SHELLPACK check_external_install_required blasbuild     blasbuild-${BLAS_VERSION}         ${BLAS_VERSION}
