#!/bin/bash
###SHELLPACK preamble thpscale 0

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK self_extract thpscale.c 
install-depends libnuma-devel

mkdir $SHELLPACK_SOURCES/thpscale-${VERSION}-installed
gcc -Wall -lpthread -lnuma $SHELLPACK_TEMP/thpscale.c -o $SHELLPACK_SOURCES/thpscale-${VERSION}-installed/thpscale || \
	die Failed to build thpscale

echo thpscale installed successfully
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file thpscale.c
