#!/bin/bash
###SHELLPACK preamble netcdffcbuild v4.5.2
GIT_LOCATION=https://github.com/Unidata/netcdf-fortran
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch netcdffcbuild-${VERSION}.tar.gz netcdffcbuild-${VERSION}
###SHELLPACK build_start netcdffcbuild-${VERSION}

ARCHSTRING="optflags: `uname -m`"
OPTFLAGS=`grep "^$ARCHSTRING" /usr/lib/rpm/rpmrc | sed -e "s/^$ARCHSTRING//"`
if [ "$OPTFLAGS" != "" ]; then
	export CFLAGS_EXTRA=" $OPTFLAGS"
	export CXXFLAGS_EXTRA=" $OPTFLAGS"
	export FCFLAGS_EXTRA=" $OPTFLAGS"
fi

export CPPFLAGS="-I$SHELLPACK_SOURCES/netcdf-installed/include"
export LDFLAGS="-L$SHELLPACK_SOURCES/netcdf-installed/lib64"
export LD_LIBRARY_PATH="$SHELLPACK_SOURCES/netcdf-installed/lib64:$LD_LIBRARY_PATH"

###SHELLPACK build_configure netcdffcbuild-${VERSION}
###SHELLPACK make_make_install

echo netcdf-fortran installed successfully
