#!/bin/bash
###SHELLPACK preamble netcdffcbuild v4.5.2
GIT_LOCATION=https://github.com/Unidata/netcdf-fortran
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch netcdffcbuild-${VERSION}.tar.gz netcdffcbuild-${VERSION}
###SHELLPACK build_start netcdffcbuild-${VERSION}

export CFLAGS+=" -I$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed/include -I$SHELLPACK_SOURCES/netcdfcbuild-$NETCDFC_VERSION-installed/include"
export LDFLAGS+=" -L$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed/$MMTESTS_LIBDIR -L$SHELLPACK_SOURCES/netcdfcbuild-$NETCDFC_VERSION-installed/$MMTESTS_LIBDIR"
export LD_LIBRARY_PATH="$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed/$MMTESTS_LIBDIR:$SHELLPACK_SOURCES/netcdfcbuild-$NETCDFC_VERSION-installed/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"

###SHELLPACK build_configure netcdffcbuild-${VERSION}
###SHELLPACK make_make_install

echo netcdf-fortran installed successfully
