#!/bin/bash
###SHELLPACK preamble netcdffcbuild v4.5.2
GIT_LOCATION=https://github.com/Unidata/netcdf-fortran
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch netcdffcbuild-${VERSION}.tar.gz netcdffcbuild-${VERSION}
###SHELLPACK build_start netcdffcbuild-${VERSION}

export CC=mpicc
export FC=mpif90
export F77=mpif77

# Install openmpi requirements
###SHELLPACK mpi_setup_deps NETCDFFC_OPENMPI_VERSION
###SHELLPACK mpi_setup_env NETCDFFC_OPENMPI_VERSION NETCDFFC_MPI_PATH NETCDFFC_MPI_LIBPATH
###SHELLPACK mpi_setup_shmem

HDF5="$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed"
NETCDFC="$SHELLPACK_SOURCES/netcdfcbuild-$NETCDFC_VERSION-installed"
PNETCDF="$SHELLPACK_SOURCES/pnetcdfbuild-$PNETCDF_VERSION-installed"

export  CFLAGS+=" -I$MPI_BASE_DIR/include -I$HDF5/include -I$NETCDFC/include -I$PNETCDF/include"
export LDFLAGS+=" -L$MPI_BASE_DIR/$MMTESTS_LIBDIR -L$HDF5/$MMTESTS_LIBDIR -L$NETCDFC/$MMTESTS_LIBDIR -L$PNETCDF/$MMTESTS_LIBDIR"
export LD_LIBRARY_PATH="$MPI_BASE_DIR/$MMTESTS_LIBDIR:$HDF5/$MMTESTS_LIBDIR:$PNETCDF/$MMTESTS_LIBDIR:$NETCDFC/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"

export WRFIO_NCD_LARGE_FILE_SUPPORT=1

###SHELLPACK build_configure netcdffcbuild-${VERSION} --disable-static --enable-shared --enable-parallel-tests --enable-large-file-tests --enable-largefile
###SHELLPACK make_make_install

echo netcdf-fortran installed successfully
