#!/bin/bash
# Run vdsotest benchmark

###SHELLPACK preamble vdsotest-bench 0

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam   --iterations	VDSOTEST_ITERATIONS
###SHELLPACK parseargParam   --duration		VDSOTEST_DURATION
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK check_install_required vdsotest-${VERSION}
###SHELLPACK init_complete

VDSOTEST_CLOCKS="clock-gettime-monotonic clock-getres-monotonic clock-gettime-monotonic-coarse clock-getres-monotonic-coarse clock-gettime-realtime clock-getres-realtime clock-gettime-realtime-coarse clock-getres-realtime-coarse clock-getres-realtime-coarse getcpu gettimeofday "

echo $VDSOTEST_CLOCKS > $LOGDIR_RESULTS/workloads
for WORKLOAD in $VDSOTEST_CLOCKS; do
	BENCH_CMD="vdsotest -d $VDSOTEST_DURATION $WORKLOAD bench"
	log_cmd "$BENCH_CMD"
	mmtests_activity $WORKLOAD
	monitor_pre_hook $LOGDIR_RESULTS $WORKLOAD
	LOG_WORKLOAD=`echo $WORKLOAD | sed -e 's/-/_/g'`
	###SHELLPACK iteration_begin $VDSOTEST_ITERATIONS
		printf "%-35s Iteration $ITERATION/$VDSOTEST_ITERATIONS\n" $WORKLOAD
		./$BENCH_CMD &> $LOGDIR_RESULTS/benchlog-${LOG_WORKLOAD}-_-${ITERATION} ||
			die "Failed to run vdso $WORKLOAD ($LOGDIR_RESULTS/benchlog-${LOG_WORKLOAD}-_-${ITERATION})"
	###SHELLPACK iteration_end $ITERATIONS
	monitor_post_hook $LOGDIR_RESULTS $WORKLOAD
done

exit $SHELLPACK_SUCCESS
