#!/bin/bash
###SHELLPACK preamble poundsyscall 0

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK self_extract pound_getppid.c 

TESTBIN="pound_getppid"

mkdir $SHELLPACK_SOURCES/poundsyscall-${VERSION}-installed
mv $SHELLPACK_TEMP/${TESTBIN}.c $SHELLPACK_SOURCES/poundsyscall-${VERSION}-installed/${TESTBIN}.c ||
	die "Failed to move ${TESTBIN}.c into install directory"

echo poundsyscall installed successfully
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file pound_getppid.c
