#!/bin/bash

###SHELLPACK preamble speccpu2017-install 1.0.5
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/proprietary/spec"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch speccpu2017-${VERSION}.tar.xz speccpu2017-${VERSION}-installed
###SHELLPACK build_start speccpu2017-${VERSION}-installed

SCRIPT=`mktemp`
echo "spawn ./install.sh
expect \"Is this correct?\" {exp_send yes\r }
while {1} {
	expect \"Installation successful\" exit
}" > $SCRIPT
expect -f $SCRIPT || die Failed to install SPECcpu 2017
rm $SCRIPT

exit $SHELLPACK_SUCCESS
