#!/bin/bash

###SHELLPACK preamble parsecbuild-install 0
GIT_LOCATION="https://github.com/cirosantilli/parsec-benchmark"
MIRROR_LOCATION="$WEBROOT/parsec/"

for PACKAGE in gsl-devel libgsl23 libgslcblas0 libjpeg8-devel libjpeg8 xt cmake libXt-devel libXmu-devel libXi-devel; do
	install-depends $PACKAGE
done

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK git_fetch parsecbuild-${VERSION}.tar.gz parsecbuild-${VERSION}-installed
cd $SHELLPACK_SOURCES
mv parsecbuild-${VERSION}-installed $SHELLPACK_DATA || die "Failed to move sources to data directory"
ln -s $SHELLPACK_DATA/parsecbuild-${VERSION}-installed parsecbuild-${VERSION}-installed
cd $SHELLPACK_SOURCES || die "Failed to cd to sources"

echo Fetching native input data
file_fetch http://parsec.cs.princeton.edu/download/3.0/parsec-3.0-input-native.tar.gz \
	$MIRROR_LOCATION/parsec-3.0-input-native.tar.gz \
	parsec-input.tar.gz
tar -xf parsec-input.tar.gz --strip-components=1 || die "Failed to download and extract parsec-input.tar.gz"

# Build fixes
for FILE in `find -name "*.cpp"`; do
	sed -i -e 's/"__PARSEC_XSTRING/" __PARSEC_XSTRING/' $FILE
done

echo parsecbuild preliminary download complete
exit $SHELLPACK_SUCCESS
