#!/bin/bash
###SHELLPACK preamble mlc-install 3.4
WEB_LOCATION=NOT_AVAILABLE
MIRROR_LOCATION="$WEBROOT/mlc/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

rm -rf $SHELLPACK_SOURCES/mlc-${VERSION}
###SHELLPACK sources_fetch mlc-${VERSION}.tar.gz mlc-${VERSION}-installed
###SHELLPACK build_start mlc-${VERSION}-installed

echo mlc installed successfully
exit $SHELLPACK_SUCCESS
