#!/bin/bash
###SHELLPACK preamble dbt5-install 0

GIT_LOCATION=https://github.com/petergeoghegan/dbt5
MIRROR_LOCATION="$WEBROOT/dbt5/"

###SHELLPACK parseargBegin
###SHELLPACK parseargParam	--dbdriver	DBDRIVER
###SHELLPACK parseargEnd

install-depends cmake

###SHELLPACK self_extract unistd-include.patch
###SHELLPACK self_extract string-boundary-check.patch

# Select database driver
case $DBDRIVER in
postgres)
	echo Checking postgres installation
	DBDRIVER_VERSION=9.3.4
	;;
*)
	die Unrecognised dbdriver $DBDRIVER
	;;
esac

# Build database and start it for sysbench config
$SHELLPACK_INCLUDE/shellpack-bench-${DBDRIVER}build --start \
        --effective_cachesize $((MEMTOTAL_BYTES*6/10)) \
        --shared_buffers $((MEMTOTAL_BYTES/4)) \
        --work_mem $((16*1048576)) || die Failed to get usable database installation

echo Building dbt5 for $DBDRIVER
export PATH=$SHELLPACK_SOURCES/${DBDRIVER}build-${DBDRIVER_VERSION}-installed/bin:$PATH
###SHELLPACK git_fetch dbt5-${VERSION}.tar.gz dbt5-${VERSION}
###SHELLPACK build_start dbt5-${VERSION}
sed -i -e 's/-E SQL_ASCII/-E SQL_ASCII -T template0/' scripts/pgsql/dbt5-pgsql-create-db
cat $SHELLPACK_TEMP/unistd-include.patch        | patch -p1 || Die Failed to apply unistd patch
cat $SHELLPACK_TEMP/string-boundary-check.patch | patch -p1 || Die Failed to apply string boundary patch
cmake CMakeLists.txt -DDBMS=pgsql || die Failed to run cmake

cd $SHELLPACK_SOURCES/dbt5-${VERSION}/egen/prj || die Failed to cd egen/prj
make -f Makefile.pgsql || die Failed to make Makefile.pgsql

cd $SHELLPACK_SOURCES/dbt5-${VERSION}/storedproc/pgsql/c || die Failed to cd storedproc/pgsql/c
make -j$NUMCPUS || die Failed to make storedproc/pgsql/c
make install    || die Failed to install storedproc to postgres

cd $SHELLPACK_SOURCES/dbt5-${VERSION} || die Failed to cd to toplevel
make -j$NUMCPUS || die Failed to build CMakeLists.txt
make install DESTDIR=$SHELLPACK_SOURCES/dbt5-${VERSION}-installed || die Failed to install

echo dbt5 for $DBDRIVER successfully installed
exit $SHELLPACK_SUCCESS

==== BEGIN unistd-include.patch ====
diff --git a/src/include/CSocket.h b/src/include/CSocket.h
index 8bf5ffd..d874f57 100644
--- a/src/include/CSocket.h
+++ b/src/include/CSocket.h
@@ -18,6 +18,7 @@
make install || die Failed to install storedproc to postgres
echo DEBUG HERE
read INPUT

cd $SHELLPACK_SOURCES/dbt5-${VERSION} || die Failed to cd to toplevel
make -j$NUMCPUS || die Failed to build CMakeLists.txt
make install DESTDIR=$SHELLPACK_SOURCES/dbt5-${VERSION}-installed || die Failed to install

echo dbt5 for $DBDRIVER successfully installed
exit $SHELLPACK_SUCCESS

==== BEGIN unistd-include.patch ====
diff --git a/src/include/CSocket.h b/src/include/CSocket.h
index 8bf5ffd..d874f57 100644
--- a/src/include/CSocket.h
+++ b/src/include/CSocket.h
@@ -18,6 +18,7 @@
 #include <netinet/in.h>
 #include <arpa/inet.h>
 #include <errno.h>
+#include <unistd.h>
 
 #include "CThreadErr.h"
 #include "MiscConsts.h"
diff --git a/src/interfaces/TxnHarnessSendToMarket.cpp b/src/interfaces/TxnHarnessSendToMarket.cpp
index 1fa1988..6dfb375 100644
--- a/src/interfaces/TxnHarnessSendToMarket.cpp
+++ b/src/interfaces/TxnHarnessSendToMarket.cpp
@@ -8,6 +8,7 @@
  * 30 July 2006
  */
 
+#include <unistd.h>
 #include "TxnHarnessSendToMarket.h"
 
 CSendToMarket::CSendToMarket(ofstream* pfile, int MEport)
==== END unistd-include.patch ====

==== BEGIN string-boundary-check.patch ====
diff --git a/storedproc/pgsql/c/trade_update.c b/storedproc/pgsql/c/trade_update.c
index ad8e3a5d42e7..b99f63b446dd 100644
--- a/storedproc/pgsql/c/trade_update.c
+++ b/storedproc/pgsql/c/trade_update.c
@@ -1241,7 +1241,7 @@ Datum TradeUpdateFrame3(PG_FUNCTION_ARGS)
 						sprintf(ct_name, "%s %s shares of %s", type_name,
 								quantity, s_name);
 					}
-					for (i = 0; i < CT_NAME_LEN || ct_name[i] != '\0'; i++) {
+					for (i = 0; i < CT_NAME_LEN && ct_name[i] != '\0'; i++) {
 						if (ct_name[i] == '\'')
 							ct_name_esc[k++] = '\\';
 						ct_name_esc[k++] = ct_name[i];
==== END string-boundary-check.patch ====
