#!/bin/bash
###SHELLPACK preamble dbt5-install 0

GIT_LOCATION=git://osdldbt.git.sourceforge.net/gitroot/osdldbt/dbt5
MIRROR_LOCATION="$WEBROOT/dbt5/"

###SHELLPACK parseargBegin
###SHELLPACK parseargParam	--dbdriver	DBDRIVER
###SHELLPACK parseargEnd

install-depends cmake

###SHELLPACK self_extract unistd-include.patch

# Select database driver
case $DBDRIVER in
postgres)
	echo Checking postgres installation
	DBDRIVER_VERSION=9.3.4
	;;
*)
	die Unrecognised dbdriver $DBDRIVER
	;;
esac

# Build database and start it for sysbench config
$SHELLPACK_INCLUDE/shellpack-bench-${DBDRIVER}build -v $DBDRIVER_VERSION --start \
        --effective_cachesize $((MEMTOTAL_BYTES*6/10)) \
        --shared_buffers $((MEMTOTAL_BYTES/4)) \
        --work_mem $((16*1048576)) || die Failed to get usable database installation

echo Building dbt5 for $DBDRIVER
export PATH=$SHELLPACK_SOURCES/${DBDRIVER}build-${DBDRIVER_VERSION}-installed/bin:$PATH
###SHELLPACK git_fetch dbt5-${VERSION}.tar.gz dbt5-${VERSION}
###SHELLPACK build_start dbt5-${VERSION}
sed -i -e 's/-E SQL_ASCII/-E SQL_ASCII -T template0/' scripts/pgsql/dbt5-pgsql-create-db
cat $SHELLPACK_TEMP/unistd-include.patch        | patch -p1 || die Failed to apply unistd patch
cmake CMakeLists.txt -DDBMS=pgsql || die Failed to run cmake

cd $SHELLPACK_SOURCES/dbt5-${VERSION}/egen/prj || die Failed to cd egen/prj
make -f Makefile.pgsql || die Failed to make Makefile.pgsql

cd $SHELLPACK_SOURCES/dbt5-${VERSION}/storedproc/pgsql/c || die Failed to cd storedproc/pgsql/c
make -j$NUMCPUS || die Failed to make storedproc/pgsql/c
make install    || die Failed to install storedproc to postgres

cd $SHELLPACK_SOURCES/dbt5-${VERSION} || die Failed to cd to toplevel
make -j$NUMCPUS || die Failed to build CMakeLists.txt
make install DESTDIR=$SHELLPACK_SOURCES/dbt5-${VERSION}-installed || die Failed to install

echo dbt5 for $DBDRIVER successfully installed
exit $SHELLPACK_SUCCESS

==== BEGIN unistd-include.patch ====
diff --git a/src/include/CSocket.h b/src/include/CSocket.h
index 8bf5ffd..d874f57 100644
--- a/src/include/CSocket.h
+++ b/src/include/CSocket.h
@@ -18,6 +18,7 @@
 #include <netinet/in.h>
 #include <arpa/inet.h>
 #include <errno.h>
+#include <unistd.h>
 
 #include "CThreadErr.h"
 #include "MiscConsts.h"
diff --git a/src/interfaces/TxnHarnessSendToMarket.cpp b/src/interfaces/TxnHarnessSendToMarket.cpp
index 1fa1988..6dfb375 100644
--- a/src/interfaces/TxnHarnessSendToMarket.cpp
+++ b/src/interfaces/TxnHarnessSendToMarket.cpp
@@ -8,6 +8,7 @@
  * 30 July 2006
  */
 
+#include <unistd.h>
 #include "TxnHarnessSendToMarket.h"
 
 CSendToMarket::CSendToMarket(ofstream* pfile, int MEport)
==== END unistd-include.patch ====
