#!/bin/bash
###SHELLPACK preamble lkp-install 0
GIT_LOCATION=git://git.kernel.org/pub/scm/linux/kernel/git/wfg/lkp-tests.git
MIRROR_LOCATION="$WEBROOT/lkp/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

install-depends pigz pbzip2 pixz plzip

###SHELLPACK git_fetch lkp-${VERSION}.tar.gz lkp-${VERSION}-installed

###SHELLPACK build_start lkp-${VERSION}-installed

echo Intel LKP installed successfully
exit $SHELLPACK_SUCCESS
