#!/bin/bash
###SHELLPACK preamble mpas v6.2
GIT_LOCATION=https://github.com/MPAS-Dev/MPAS-Model
MIRROR_LOCATION="$WEBROOT/mpas/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK mpi_setup_deps MPAS_OPENMPI_VERSION
###SHELLPACK mpi_setup_env MPAS_OPENMPI_VERSION MPAS_MPI_PATH MPAS_MPI_LIBPATH

###SHELLPACK git_fetch mpas-${VERSION}.tar.gz mpas-${VERSION}-installed
###SHELLPACK build_start mpas-${VERSION}-installed

# Additional configuration to build MPAS in both x86_64 and aaarch64:
#- removes -m64
#- adds -fallow-invalid-boz
#- use $(MMTESTS_LIBDIR) instead of "lib"
sed -i -e "s/\-m64 //" Makefile
sed -i -e "s/FFLAGS_PROMOTION = \-fdefault\-real\-8 \-fdefault\-double\-8/FFLAGS_PROMOTION = \-fdefault\-real\-8 \-fdefault\-double\-8 \-fallow\-invalid\-boz/" Makefile
sed -i -e "s/\-L\$(PNETCDF)\/lib/\-L\$(PNETCDF)\/\$(MMTESTS_LIBDIR)/" Makefile

export PIO="$SHELLPACK_SOURCES/mpasdeps-installed"
export PNETCDF="$SHELLPACK_SOURCES/mpasdeps-installed"


case $MPAS_MODEL in
atmosphere)
    ###SHELLPACK make gfortran CORE=init_atmosphere USE_PIO2=true
    ###SHELLPACK make gfortran CORE=atmosphere USE_PIO2=true AUTOCLEAN=true
    ;;
*)
	die "Unrecognised model $MPAS_MODEL, failed to build"
esac

echo mpas installed successfully
exit $SHELLPACK_SUCCESS
