#!/bin/bash
# fs-mark installer
###SHELLPACK preamble fsmark-install 3.3
WEB_LOCATION=https://10gbps-io.dl.sourceforge.net/project/fsmark/fsmark
MIRROR_LOCATION="$WEBROOT/fsmark/"

install-depends glibc-devel-static glibc-devel-static-32bit

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch $VERSION/fs_mark-${VERSION}.tar.gz fsmark-${VERSION}-installed

###SHELLPACK build_start fsmark-${VERSION}-installed
###SHELLPACK make

echo fsmark installed successfully
