#!/bin/bash
# This script installs fsmark and runs the regression tests

###SHELLPACK preamble fsmark-bench 3.3
MIN_THREADS=1
MAX_THREADS=1
NUM_SUB_DIRECTORIES=100
NUM_FILES_PER_ITERATION=50000
NUM_ITERATIONS=63
FILESIZE=0

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam --min-threads            MIN_THREADS
###SHELLPACK parseargParam --max-threads            MAX_THREADS
###SHELLPACK parseargParam --filesize               FILESIZE
###SHELLPACK parseargParam --nr-files-per-iteration NUM_FILES_PER_ITERATION
###SHELLPACK parseargParam --nr-sub-directories     NUM_SUB_DIRECTORIES
###SHELLPACK parseargParam --iterations             NUM_ITERATIONS
###SHELLPACK parseargEnd

###SHELLPACK check_install_required fsmark-${VERSION}

###SHELLPACK monitor_hooks

ln -s $SHELLPACK_TEMP /tmp/fsmark-$$

###SHELLPACK threads_large_stride_begin $MIN_THREADS $MAX_THREADS
	PARAM=
	for THREAD in `seq 1 $NR_THREADS`; do
		mkdir -p /tmp/fsmark-$$/$THREAD
		PARAM="$PARAM -d /tmp/fsmark-$$/$THREAD"
	done

	echo ./fs_mark \
		$PARAM \
		-D $NUM_SUB_DIRECTORIES \
		-n $(($NUM_FILES_PER_ITERATION/$NR_THREADS)) \
		-L $NUM_ITERATIONS \
		-t $NR_THREADS \
		-S0 \
		-s $FILESIZE | tee $LOGDIR_RESULTS/fsmark-cmd-${NR_THREADS}.log

	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
	eval ./fs_mark \
		$PARAM \
		-D $NUM_SUB_DIRECTORIES \
		-n $(($NUM_FILES_PER_ITERATION/$NR_THREADS)) \
		-L $NUM_ITERATIONS \
		-t $NR_THREADS \
		-S0 \
		-s $FILESIZE \
			2>&1 | tee $LOGDIR_RESULTS/fsmark-${NR_THREADS}.log \
				|| die Failed to run fsmark
	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
	rm -rf $SHELLPACK_TEMP/*
###SHELLPACK threads_stride_end

rm /tmp/fsmark-$$

exit $SHELLPACK_SUCCESS
