#!/bin/bash
# phpbench installer
###SHELLPACK preamble phpbench-install 0.8.1

WEB_LOCATION=https://download.pureftpd.org/pub/phpbench
MIRROR_LOCATION="$WEBROOT/phpbench/"
APACHE_VERSION=2.4.17
APR_VERSION=1.5.2
PCRE_VERSION=8.35

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK check_external_install_required_continue apachebuild apache-build-${APACHE_VERSION} ${APACHE_VERSION}
###SHELLPACK sources_fetch phpbench-${VERSION}.tar.gz phpbench-${VERSION}-installed

echo phpbench successfully
exit $SHELLPACK_SUCCESS
