#!/bin/bash
###SHELLPACK preamble netcdfcbuild v4.7.3
GIT_LOCATION=https://github.com/Unidata/netcdf-c
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

export MMTESTS_NO_BUILDFLAGS=yes
###SHELLPACK git_fetch netcdfcbuild-${VERSION}.tar.gz netcdfcbuild-${VERSION}
###SHELLPACK build_start netcdfcbuild-${VERSION}

ARCHSTRING="optflags: `uname -m`"
OPTFLAGS=`grep "^$ARCHSTRING" /usr/lib/rpm/rpmrc | sed -e "s/^$ARCHSTRING//"`
if [ "$OPTFLAGS" != "" ]; then
	export CFLAGS=$OPTFLAGS
	export CXXFLAGS=$OPTFLAGS
	export FCFLAGS=$OPTFLAGS
fi

###SHELLPACK build_configure netcdfcbuild-${VERSION}
###SHELLPACK make_make_install
###SHELLPACK install_merge netcdfcbuild-${VERSION} netcdf-installed

echo netcdf-c installed successfully
