#!/bin/bash
###SHELLPACK preamble netcdfcbuild v4.7.3
GIT_LOCATION=https://github.com/Unidata/netcdf-c
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch netcdfcbuild-${VERSION}.tar.gz netcdfcbuild-${VERSION}
###SHELLPACK build_start netcdfcbuild-${VERSION}

export CFLAGS+=" -I$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed/include"
export LDFLAGS+=" -L$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed/$MMTESTS_LIBDIR"
export LD_LIBRARY_PATH="$SHELLPACK_SOURCES/hdf5build-$HDF5_VERSION-installed/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"

echo DEBUG: $CFLAGS
echo DEBUG: $LDFLAGS
echo DEBUG: $LD_LIBRARY_PATH

###SHELLPACK build_configure netcdfcbuild-${VERSION}
###SHELLPACK make_make_install

echo netcdf-c installed successfully
