#!/bin/bash
# dbench installer
###SHELLPACK preamble dbench-install 3.04
GIT_LOCATION=git://git.samba.org/sahlberg/dbench.git
WEB_LOCATION=http://samba.org/ftp/tridge/dbench/
MIRROR_LOCATION="$WEBROOT/dbench/"

install-depends popt-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch dbench-${VERSION}.tar.gz dbench-${VERSION}

# Build
###SHELLPACK build_start dbench-${VERSION}
###SHELLPACK build_autogen dbench-${VERSION}
###SHELLPACK build_configure dbench-${VERSION}
###SHELLPACK make_make_install

# Fixups
if [ ! -e $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share ]; then
	cp $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share/doc/dbench/loadfiles/client.txt $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share
fi

# Extract our loadfiles from the original one
head -n 600 $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share/client.txt >$SHELLPACK_SOURCES/dbench-${VERSION}-installed/share/client-warmup.txt
head -n 4173 $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share/client.txt | tail -n 3573 >$SHELLPACK_SOURCES/dbench-${VERSION}-installed/share/client-tiny.txt

echo dbench installed successfully
