#!/bin/bash
###SHELLPACK preamble dbench-bench ed505f4eafb7

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

# Common dbench switches
LOADDIR="$SHELLPACK_SOURCES/dbench-${VERSION}-installed/share"
if [ "$DBENCH_OSYNC" = "yes" ]; then
	DBENCH_OSYNC_COMMAND=-s
fi
if [ "$DBENCH_SYNC_DIRECTORY" = "yes" ]; then
	DBENCH_SYNC_COMMAND=-S
fi
if [ "$DBENCH_FSYNC" = "yes" ]; then
	DBENCH_FSYNC_COMMAND=-F
fi

# Init min client
if [ "$DBENCH_MIN_CLIENTS" = "" ]; then
	DBENCH_MIN_CLIENTS=1
fi

# Dbench install and warmup, init only
###SHELLPACK init_only_start
###SHELLPACK check_install_required_continue dbench-${VERSION}
###SHELLPACK init_only_end

cd $SHELLPACK_SOURCES/dbench-${VERSION}-installed || die "Failed to cd to dbench install directory"
###SHELLPACK threads_large_stride_begin $DBENCH_MIN_CLIENTS $DBENCH_MAX_CLIENTS

	mmtests_activity client $NR_THREADS

	# Init
	echo dbench init $NR_THREADS
	rm -rf $SHELLPACK_DATA/clients &>/dev/null
	./bin/dbench --run-once --skip-cleanup -D $SHELLPACK_DATA \
		--loadfile $LOADDIR/client-warmup.txt $NR_THREADS &>/dev/null

	# Execute
	echo dbench run $NR_THREADS/$DBENCH_MAX_CLIENTS
	BENCH_CMD="dbench $DBENCH_OSYNC_COMMAND $DBENCH_SYNC_COMMAND $DBENCH_FSYNC_COMMAND \
		-D $SHELLPACK_DATA --warmup 0 \
		-t $((DBENCH_DURATION_BASE + FACTOR*CLIENT/1000)) \
		--loadfile $LOADDIR/client-tiny.txt --show-execute-time \
		$NR_THREADS"
	log_cmd $BENCH_CMD
	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
	./bin/$BENCH_CMD &> $LOGDIR_RESULTS/dbench-$NR_THREADS.log
	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS

	grep "completed in" $LOGDIR_RESULTS/dbench-$NR_THREADS.log | sort -n -k8	> $LOGDIR_RESULTS/benchlog-loadfile-$NR_THREADS
	sed -e "/completed in/d" $LOGDIR_RESULTS/dbench-$NR_THREADS.log 		> $LOGDIR_RESULTS/remainder
	grep execute $LOGDIR_RESULTS/remainder						> $LOGDIR_RESULTS/benchlog-tput-$NR_THREADS
	grep -A 99 Operation $LOGDIR_RESULTS/remainder \
		| sed -e '/-----/d' -e '/^$/d' -e '/Throughput/d' -e '/Operation/d'	> $LOGDIR_RESULTS/benchlog-op-$NR_THREADS

	rm -f $LOGDIR_RESULTS/remainder
	xz $LOGDIR_RESULTS/dbench-$NR_THREADS.log
	xz $LOGDIR_RESULTS/benchlog-tput-$NR_THREADS
	xz $LOGDIR_RESULTS/benchlog-loadfile-$NR_THREADS
	xz $LOGDIR_RESULTS/benchlog-op-$NR_THREADS
###SHELLPACK threads_stride_end

exit $SHELLPACK_SUCCESS
