#!/bin/bash
# This script installs Apache Maven and leaves it ready for use building 'linkbench'
###SHELLPACK preamble mavenbuild-bench 3.3.9
MAVEN_VERSION=3.3.9

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK check_install_required mavenbuild-${VERSION}

echo maven successfully installed
exit $SHELLPACK_SUCCESS
