#!/bin/bash
# Apache Maven installer.
###SHELLPACK preamble mavenbuild-install 3.3.9
WEB_LOCATION=http://apache.mirrors.tds.net/maven/maven-3/3.3.9/binaries/
#MIRROR_LOCATION="$WEBROOT/maven/"

MAVEN_VERSION=3.3.9

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch apache-maven-${MAVEN_VERSION}-bin.tar.gz mavenbuild-${MAVEN_VERSION}-installed
###SHELLPACK build_start mavenbuild-${MAVEN_VERSION}-installed

echo maven installed successfully
