#!/bin/bash
# lhcs regression test installer
###SHELLPACK preamble lhcs-install 1.6
WEB_LOCATION=https://raw.githubusercontent.com/autotest/autotest-client-tests/master/cpu_hotplug
MIRROR_LOCATION="$WEBROOT/lhcs/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch lhcs_regression-${VERSION}.tgz lhcs-${VERSION}-installed

echo lhcs installed successfully
