#!/bin/bash
###SHELLPACK preamble lhcs-bench 1.6

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK check_install_required lhcs-${VERSION}

# Run test
cd $SHELLPACK_SOURCES/lhcs-${VERSION}-installed || die Failed to cd to lhcs directory
./runtests.sh

exit $SHELLPACK_SUCCESS
