#!/bin/bash
# Benchmark a number of kernel builds
###SHELLPACK preamble kernbench-bench 6.15
ITERATIONS=5
KERNBENCH_CONFIG=defconfig
KERNBENCH_TARGETS=vmlinux
KERNBENCH_WARMUP=no

install-depends flex bison libelf-devel libopenssl-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam	--min-threads	KERNBENCH_MIN_THREADS
###SHELLPACK parseargParam	--max-threads	KERNBENCH_MAX_THREADS
###SHELLPACK parseargParam	--iterations	KERNBENCH_ITERATIONS
###SHELLPACK parseargParam	--kernel-config	KERNBENCH_CONFIG
###SHELLPACK parseargParam	--build-targets	KERNBENCH_TARGETS
###SHELLPACK parseargYes	--warmup	KERNBENCH_WARMUP
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK init_only_start
###SHELLPACK check_install_required_continue kernbench-${VERSION}
	# Setup source
	cd $SHELLPACK_DATA || die "Failed to change to $SHELLPACK_DATA"
	rm -rf linux-$VERSION

	echo Setup kernel source on test data directory
	tar -xf $SHELLPACK_SOURCES/linux-$VERSION.tar.xz || die "Failed to extract $SHELLPACK_SOURCES/linux-$VERSION.tar.xz"
	cd linux-$VERSION || die "Unexpected directory layout for source, no $SHELLPACK_DATA/linux-$VERSION/"
	make -j$NUMCPUS mrproper &>/dev/null || die "Failed to clean"

	# Configure and warmup if requested
	yes '' | make $KERNBENCH_CONFIG &>/dev/null || die "Failed to make $KERNBENCH_CONFIG"
	if [ "$KERNBENCH_WARMUP" = "yes" ]; then
		echo Install-only warming run
		make $COMPILER_FLAGS -j$NUMCPUS $KERNBENCH_TARGETS > /dev/null 2>&1 || die "Failed to build $KERNBENCH_TARGETS"
	fi
	make $COMPILER_FLAGS clean >/dev/null
###SHELLPACK init_only_end

echo Clean and reconfigure source
cd $SHELLPACK_DATA/linux-$VERSION || die "Unexpected directory layout for source, no $SHELLPACK_DATA/linux-$VERSION/"
yes '' | make $KERNBENCH_CONFIG &>/dev/null || die "Failed to make $KERNBENCH_CONFIG"
make -j$NUMCPUS clean

###SHELLPACK threads_powertwo_begin $KERNBENCH_MIN_THREADS $KERNBENCH_MAX_THREADS
	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
	###SHELLPACK iteration_begin $KERNBENCH_ITERATIONS
		echo Starting threads $NR_THREADS/$KERNBENCH_MAX_THREADS iteration $ITERATION/$KERNBENCH_ITERATIONS

		save_rc $TIME_CMD make -j$NR_THREADS $KERNBENCH_TARGETS 2>> $LOGDIR_RESULTS/kernbench-${NR_THREADS}-$ITERATION.time > /dev/null
		grep elapsed $LOGDIR_RESULTS/kernbench-${NR_THREADS}-$ITERATION.time
		recover_rc
		if [ $? -ne 0 ]; then
			die "Failed to run kernbench"
		fi

		# cleanup
		make clean >/dev/null
	###SHELLPACK iteration_end $ITERATIONS
	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
###SHELLPACK threads_powertwo_end

# Cleanup
cd /
rm -rf $SHELLPACK_DATA/linux-$VERSION

exit $SHELLPACK_SUCCESS
