#!/bin/bash
###SHELLPACK preamble pedsort-install 1
GIT_LOCATION=https://pdos.csail.mit.edu/mosbench/mosbench.git
MIRROR_LOCATION="$WEBROOT/mosbench/"

install-depends libdb-devel
if [ ! -e /usr/include/db.h ]; then
	install-depends libdb-4_8-devel
fi
install-depends python
install-depends python3
install-depends gcc-c++

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch pedsort-${VERSION}.tar.gz pedsort-${VERSION}-installed

###SHELLPACK build_start pedsort-${VERSION}-installed
###SHELLPACK self_extract 0001-glibc.patch
###SHELLPACK self_extract 0002-python3.patch
cat $SHELLPACK_TEMP/0001-glibc.patch | patch -p1 || die "Failed to patch psearchy/mkdb"

if [ ! -e /usr/bin/python -a -e /usr/bin/python3 ]; then
	cat $SHELLPACK_TEMP/0002-python3.patch | patch -p1 || "Failed to patch mkprimes"
fi

###SHELLPACK make -C psearchy/mkdb/

echo pedsort installed successfully
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file 0001-glibc.patch
###SHELLPACK include_file 0002-python3.patch
