#!/bin/bash
# pedsort

###SHELLPACK preamble pedsort-bench 1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam   --min-threads      PEDSORT_MIN_THREADS
###SHELLPACK parseargParam   --max-threads      PEDSORT_MAX_THREADS
###SHELLPACK parseargParam   --iterations	PEDSORT_ITERATIONS
###SHELLPACK parseargParam   --nfiles		PEDSORT_NFILES
###SHELLPACK parseargParam   --nwords-file	PEDSORT_NFILES_WORDS
###SHELLPACK parseargParam   --cache		PEDSORT_CACHE
###SHELLPACK parseargParam   --tmpfs		PEDSORT_TMPFS
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

PEDSORT_DIR=$SHELLPACK_SOURCES/pedsort-${VERSION}-installed/psearchy/mkdb
PEDSORT_WORDS_DIR=$PEDSORT_DIR/words
PEDSORT_CMD=${PEDSORT_DIR}/pedsort
WORDS_CMD=${PEDSORT_DIR}/generate-words.pl

cleanup() {
	rm -rf  $SHELLPACK_TEMP/db/*
	umount $SHELLPACK_TEMP/db &>/dev/null
}
trap cleanup EXIT

###SHELLPACK init_only_start
###SHELLPACK check_install_required_continue pedsort-${VERSION}
mkdir -p $PEDSORT_WORDS_DIR

###SHELLPACK self_extract generate-words.pl
mv $SHELLPACK_TEMP/generate-words.pl $WORDS_CMD
chmod a+x $WORDS_CMD

echo Generating text files
$WORDS_CMD -t $(( $NUMCPUS * 2 )) -w $PEDSORT_NFILES_WORDS -m bruit \
	   -f $PEDSORT_NFILES -p $PEDSORT_WORDS_DIR/text-file-%d.txt ||
		die "Failed to generate words for benchmark input."
ls --format single-column $PEDSORT_WORDS_DIR/text-file-*.txt > $PEDSORT_WORDS_DIR/pedsort-input.txt

###SHELLPACK init_only_end

echo Creating db directory structure
rm -rf $SHELLPACK_TEMP/db/
mkdir $SHELLPACK_TEMP/db/
if [ "$PEDSORT_TMPFS" = "yes" ]; then
	mount -t tmpfs none $SHELLPACK_TEMP/db/
fi
for i in $(seq 0 $(( $PEDSORT_MAX_THREADS - 1 ))); do
	mkdir -p $SHELLPACK_TEMP/db/db$i
done


if [ "$PEDSORT_CACHE" = "warm" ]; then
	echo Warming up
	mmtests_activity warmup

	$PEDSORT_CMD -t $SHELLPACK_TEMP/db/db -c $NR_THREADS < $PEDSORT_WORDS_DIR/pedsort-input.txt 2>/dev/null
fi

###SHELLPACK threads_large_stride_begin $PEDSORT_MIN_THREADS $PEDSORT_MAX_THREADS
	BENCH_CMD="$PEDSORT_CMD -t $SHELLPACK_TEMP/db/db -c $NR_THREADS < $PEDSORT_WORDS_DIR/pedsort-input.txt"
	log_cmd "$BENCH_CMD"

	mmtests_activity threads-$NR_THREADS
	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
	###SHELLPACK iteration_begin $PEDSORT_ITERATIONS
	if [ "$PEDSORT_CACHE" = "cold" ]; then
		echo Dropping caches as per requested
		sysctl -w vm.drop_caches=3

		# build the indexes from scratch
		rm -rf SHELLPACK_TEMP/db/
		for i in $(seq 0 $(( $PEDSORT_MAX_THREADS - 1 ))); do
			mkdir -p $SHELLPACK_TEMP/db/db$i
		done
	fi

	echo Running with indexing-threads $NR_THREADS/$PEDSORT_MAX_THREADS iteration $ITERATION/$PEDSORT_ITERATIONS
	eval $BENCH_CMD &> $LOGDIR_RESULTS/benchlog-${NR_THREADS}-_-${ITERATION} || die "Failed to run pedsort ($LOGDIR_RESULTS/benchlog-${NR_THREADS}-${ITERATION})"
	###SHELLPACK iteration_end
	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS

###SHELLPACK threads_stride_end

DBSIZE=$(du -sh $SHELLPACK_TEMP/db/)
echo $DBSIZE >> $LOGDIR_RESULTS/db_size.txt
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file generate-words.pl
