#!/bin/bash
# john the ripper installer
###SHELLPACK preamble johnripper-install 1.9.0-jumbo-1
WEB_LOCATION=https://www.openwall.com/john/k/
MIRROR_LOCATION="$WEBROOT/johnripper/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch john-${VERSION}.tar.xz johnripper-${VERSION}-installed

# Build
###SHELLPACK build_start johnripper-${VERSION}-installed
cd src
###SHELLPACK build_configure johnripper-${VERSION}
###SHELLPACK make

# Minimal install
cd ../
mkdir -p share/john
cp -r run/*.conf	share/john
cp -r run/rules		share/john

echo john the ripper installed successfully
