#!/bin/bash

###SHELLPACK preamble schbench-bench 6300b8f3a892

SCHBENCH_INTERVAL=10
SCHBENCH_RUNTIME=180
SCHBENCH_MESSENGER_PIN=

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam    --messengers		SCHBENCH_MESSAGE_THREADS
###SHELLPACK parseargParam    --min-workers		SCHBENCH_MIN_WORKER_THREADS
###SHELLPACK parseargParam    --max-workers		SCHBENCH_MAX_WORKER_THREADS
###SHELLPACK parseargParam    --runtime			SCHBENCH_RUNTIME
###SHELLPACK parseargParam    --interval		SCHBENCH_INTERVAL
###SHELLPACK parseargParam    --messenger-pin		SCHBENCH_MESSENGER_PIN
###SHELLPACK parseargParam    --thinktime-ops		SCHBENCH_SCHBENCH_THINKTIME_OPS
###SHELLPACK parseargParam    --thinktime-sleep		SCHBENCH_SCHBENCH_THINKTIME_SLEEP
###SHELLPACK parseargYes      --disable-spinlock	SCHBENCH_DISABLE_SPINLOCK
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK check_install_required schbench-${VERSION}
###SHELLPACK init_complete

###SHELLPACK threads_powertwo_begin $SCHBENCH_MIN_WORKER_THREADS $SCHBENCH_MAX_WORKER_THREADS
	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS

	echo Running schbench $SCHBENCH_MESSAGE_THREADS messengers, $NR_THREADS workers
	BENCH_CMD=" ./schbench -z $SCHBENCH_INTERVAL -i $SCHBENCH_INTERVAL -r $SCHBENCH_RUNTIME -m $SCHBENCH_MESSAGE_THREADS -t $NR_THREADS"
	[ "$SCHBENCH_DISABLE_SPINLOCK"	=  "yes" ]	&& BENCH_CMD+=" -L"
	[ "$SCHBENCH_MESSENGER_PIN"	!= ""    ]	&& BENCH_CMD+=" -M $SCHBENCH_MESSENGER_PIN"
	[ "$SCHBENCH_THINKTIME_OPS"	!= ""    ]	&& BENCH_CMD+=" -n $SCHBENCH_THINKTIME_OPS"
	[ "$SCHBENCH_THINKTIME_SLEEP"	!= ""    ]	&& BENCH_CMD+=" -s $SCHBENCH_THINKTIME_SLEEP"

	log_cmd "$BENCH_CMD"
	$TIME_CMD -o $LOGDIR_RESULTS/time-$NR_THREADS \
		$BENCH_CMD &> $LOGDIR_RESULTS/schbench-$NR_THREADS.log

	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
###SHELLPACK threads_powertwo_end

exit $SHELLPACK_SUCCESS
