#!/bin/bash
###SHELLPACK preamble thpcompact 0

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK self_extract thpcompact.c
install-depends libnuma-devel

mkdir $SHELLPACK_SOURCES/thpcompact-${VERSION}-installed
gcc -Wall -g -lpthread -lnuma $SHELLPACK_TEMP/thpcompact.c -o $SHELLPACK_SOURCES/thpcompact-${VERSION}-installed/thpcompact || \
	die "Failed to build thpcompact"

echo thpcompact installed successfully
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file thpcompact.c
