#!/bin/bash
# This script installs memcached and leaves it ready for benchmarking
###SHELLPACK preamble memcached-bench 1.4.13

install-depends libevent-devel

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

INSTALL_SWITCH=
###SHELLPACK init_only_start
	INSTALL_SWITCH=--install-only
###SHELLPACK init_only_continue

###SHELLPACK check_install_required_continue memcached-${VERSION} $INSTALL_SWITCH
###SHELLPACK init_complete

echo memcached successfully installed
exit $SHELLPACK_SUCCESS
