#!/bin/bash
###SHELLPACK preamble filelockperf-install 0
GIT_LOCATION=git://git.samba.org/jlayton/lockperf.git
MIRROR_LOCATION="$WEBROOT/filelockperf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch filelockperf-${VERSION}.tar.gz filelockperf-${VERSION}-installed

###SHELLPACK build_start filelockperf-${VERSION}-installed
git clone git://git.savannah.gnu.org/gnulib.git
export FULLPATH=`pwd`
export PATH=$PATH:$FULLPATH/gnulib/
./autogen.sh && ./configure
###SHELLPACK make

echo filelockperf installed successfully
