#!/bin/bash
# libmicro installer
###SHELLPACK preamble libmicro-string-install 1
GIT_LOCATION=https://github.com/redhat-performance/libMicro
MIRROR_LOCATION="$WEBROOT/extra/libmicro"

install-depends gcc

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch libmicro-string-${VERSION}.tar.gz libmicro-string-${VERSION}-installed

###SHELLPACK build_start libmicro-string-${VERSION}-installed

###SHELLPACK make_clean
###SHELLPACK make

echo libmicro installed successfully
