#!/bin/bash
###SHELLPACK preamble hdf5build hdf5-1_10_5
GIT_LOCATION=https://github.com/HDFGroup/hdf5
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch hdf5build-${VERSION}.tar.gz hdf5build-${VERSION}
###SHELLPACK build_start hdf5build-${VERSION}
###SHELLPACK build_configure hdf5build-${VERSION} --enable-fortran --enable-cxx
###SHELLPACK make_make_install

echo netcdf-c installed successfully
