#!/bin/bash
###SHELLPACK preamble hdf5build hdf5-1_10_5
GIT_LOCATION=https://github.com/HDFGroup/hdf5
MIRROR_LOCATION="$WEBROOT/netcdf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch hdf5build-${VERSION}.tar.gz hdf5build-${VERSION}
###SHELLPACK build_start hdf5build-${VERSION}

export CC=mpicc
export FC=mpif90
export CXX=mpic++

export   CFLAGS+=" -I$MPI_BASE_DIR/include"
export CXXFLAGS+=" -I$MPI_BASE_DIR/include"
export  FCFLAGS+=" -I$MPI_BASE_DIR/include"
export  LDFLAGS+=" -L$MPI_BASE_DIR/$MMTESTS_LIBDIR"
export LD_LIBRARY_PATH="$MPI_BASE_DIR/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"

###SHELLPACK build_configure hdf5build-${VERSION} --enable-fortran --enable-parallel --enable-shared
###SHELLPACK make_make_install

echo hdf5 installed successfully
