#!/bin/bash
# This is the script for running the graphdb benchmark
###SHELLPACK preamble graphdb-bench 0

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam --read-threads	GRAPHDB_READ_THREADS
###SHELLPACK parseargParam --write-threads	GRAPHDB_WRITE_THREADS
###SHELLPACK parseargParam --file-size		GRAPHDB_FILESIZE
###SHELLPACK parseargParam --workingset-size	GRAPHDB_WORKINGSET
###SHELLPACK parseargParam --duration		GRAPHDB_DURATION
###SHELLPACK parseargEnd

###SHELLPACK check_install_required graphdb
###SHELLPACK monitor_hooks

pushd $SHELLPACK_SOURCES/graphdb-${VERSION}-installed > /dev/null
RESULTSLOG=$LOGDIR_RESULTS/graphdb

# Build test program
GB=$((1048576*1024))
GRAPHDB_WORKINGSET=$(((GRAPHDB_WORKINGSET+GB)&~(GB-1)))
NR_FILES=$((GRAPHDB_WORKINGSET/GRAPHDB_FILESIZE))
sed -i -e "s/int FILE_SIZE =.*/int FILE_SIZE = $GRAPHDB_FILESIZE;/" graphdb.cpp || die Failed to edit driver
sed -i -e "s/int NUM_READ_THREADS =.*/int NUM_READ_THREADS = $GRAPHDB_READ_THREADS;/" graphdb.cpp || die Failed to edit driver
sed -i -e "s/int NUM_WRITE_THREADS =.*/int NUM_WRITE_THREADS = $GRAPHDB_WRITE_THREADS;/" graphdb.cpp || die Failed to edit driver
sed -i -e "s/int DURATION =.*/int DURATION = $GRAPHDB_DURATION;/" graphdb.cpp || die Failed to edit driver
g++ -O2 -g -Wall -lpthread graphdb.cpp -o graphdb || die Failed to build driver program
cp graphdb.cpp $LOGDIR_RESULTS

# Setup input data
cd $SHELLPACK_TEMP
mkdir mmap_set_0
mkdir mmap_set_1
mkdir mmap_live_data
for i in `seq 0 $NR_FILES`; do
	echo Creating random file ${i}.dat of $NR_FILES, size $((GRAPHDB_FILESIZE/1048576))MB
	dd if=/dev/urandom of=mmap_set_0/${i}.dat ibs=1048575 count=$((GRAPHDB_FILESIZE/1048576)) 2> /dev/null || die Failed to create file
	cp mmap_set_0/${i}.dat mmap_set_1/${i}.dat || die Failed to create file
done

# Sync and drop cache for cold start
sync
echo 3 > /proc/sys/vm/drop_caches

# Run the benchmark
mmtests_activity $CONN_NAME-$NR_THREADS
monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
$SHELLPACK_SOURCES/graphdb-${VERSION}-installed/graphdb > $LOGDIR_RESULTS/graphdb.log
monitor_post_hook $LOGDIR_RESULTS $NR_THREADS

exit $RETVAL
