#!/bin/bash
###SHELLPACK preamble pistress-install 0
GIT_LOCATION=git://git.kernel.org/pub/scm/linux/kernel/git/clrkwllms/rt-tests.git
MIRROR_LOCATION="$WEBROOT/pistress/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch pistress-${VERSION}.tar.gz pistress-${VERSION}-installed

install-depends libnuma-devel

###SHELLPACK build_start pistress-${VERSION}-installed
###SHELLPACK make

echo pistress installed successfully
