#!/bin/bash
# Netperf installer
###SHELLPACK preamble netperf-install 2.4.5
GIT_LOCATION=https://github.com/HewlettPackard/netperf
MIRROR_LOCATION="$WEBROOT/netperf/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

GIT_FETCH_BRANCH="netperf-${VERSION}"
###SHELLPACK git_fetch ${VERSION}.tar.gz netperf-${VERSION}

###SHELLPACK build_start netperf-${VERSION}

sed  -i '1i #define _GNU_SOURCE' src/netlib.c
if [ "$VERSION" = "2.7.0" ]; then
	export CFLAGS+=" -fno-strict-aliasing -fcommon"
fi

if [ ! -e ./configure ]; then
	./autogen.sh || die "Failed to run autogen"
fi

export CFLAGS+=" -DWANT_UNIX"

if (( `gcc -dumpversion` >= 14 )) ; then
   # netperf doesn't declare library, which became -Werror in gcc-14
   export CFLAGS+=" -Wno-implicit-function-declaration"
   # netperf has function declarations without parameters, breaking C23:
   export CFLAGS+=" -std=gnu17"
fi

export MMTESTS_BUILD_CONFIGURE+=" --enable-demo=yes"

###SHELLPACK build_configure netperf-${VERSION}
###SHELLPACK make_make_install

echo Netperf installed successfully
exit $SHELLPACK_SUCCESS
