#!/bin/bash
# This script installs netperf and runs the regression tests
###SHELLPACK preamble netperf-bench 2.4.5
PROTOCOLS="UDP_STREAM TCP_STREAM"
BUFFER_SIZES="64 128 256 1024 2048 3312 4096 6144 8192 10240 12288 14336 16384"

TASKSET_SERVER=
TASKSET_CLIENT=

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargBindings
	--protocols)
		PROTOCOLS=`echo $2 | sed -e 's/,/ /g'`
		shift 2
		;;
	--buffer-sizes)
		BUFFER_SIZES=`echo $2 | sed -e 's/,/ /g'`
		shift 2
		;;
###SHELLPACK parseargEnd

###SHELLPACK check_install_required netperf-${VERSION}

###SHELLPACK monitor_hooks

cd $SHELLPACK_SOURCES/netperf-${VERSION}-installed || die Failed to cd to netperf directory

echo Killing old servers
killall netserver

echo Starting server
NETROOT=$SHELLPACK_SOURCES/netperf-${VERSION}-installed 
$TASKSET_SERVER $NETROOT/bin/netserver || die Failed to start netserver
sleep 2

echo $PROTOCOLS > $LOGDIR_RESULTS/protocols
for PROTOCOL in $PROTOCOLS; do
	EXTRA=
	if [ "$PROTOCOL" = "UDP_STREAM" ]; then
		EXTRA="-P 15895 -s 32768 -S 32768"
	fi

	for SIZE in $BUFFER_SIZES; do
		SIZE_OPT=
		if [ "$PROTOCOL" = "UDP_STREAM" -o "$PROTOCOL" = "TCP_STREAM" ]; then
			SIZE_OPT="-m $SIZE -M $SIZE"
		fi
		if [ "$PROTOCOL" = "UDP_RR" -o "$PROTOCOL" = "TCP_RR" ]; then
			SIZE_OPT="-r $SIZE"
		fi
	
		echo Running test $PROTOCOL 
		monitor_pre_hook $LOGDIR_RESULTS $SIZE
		eval $TASKSET_CLIENT $NETROOT/bin/netperf \
			-t $PROTOCOL \
			-i 30,6 -I 99,1 \
			-H 127.0.0.1 \
			-- \
			$SIZE_OPT \
			$EXTRA \
				2>&1 | tee $LOGDIR_RESULTS/$PROTOCOL-${SIZE}.log \
				|| die Failed to run netperf
		monitor_post_hook $LOGDIR_RESULTS $SIZE
	done
done
killall netserver

exit $SHELLPACK_SUCCESS
