#!/bin/bash
###SHELLPACK preamble linkbench-bench 0

FIRST_DB_INSTALL=false
MARIADB_VERSION=10.1.8
MARIADB_DBNAME=linkdb
MARIADB_ADMIN_USER=root
MARIADB_ADMIN_PASSWORD=mmtests-default
MYSQLCMD="${SHELLPACK_SOURCES}/mariadbbuild-${MARIADB_VERSION}-installed/bin/mysql -u $MARIADB_ADMIN_USER -p$MARIADB_ADMIN_PASSWORD"
MYSQLADMIN="${SHELLPACK_SOURCES}/mariadbbuild-${MARIADB_VERSION}-installed/bin/mysqladmin -u $MARIADB_ADMIN_USER -p$MARIADB_ADMIN_PASSWORD"
DBSTART_OPTIONS="--innodb_flush_method=nosync,--innodb_flush_log_at_trx_commit=0,--innodb_buffer_pool_size=${BUFF_POOL_SIZE},--innodb_log_file_size=512M,--max_allowed_packet=1G"


###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam    --warmup-time  LINKBENCH_WARMUP_TIME
###SHELLPACK parseargParam    --min-threads  LINKBENCH_MIN_THREADS
###SHELLPACK parseargParam    --max-threads  LINKBENCH_MAX_THREADS
###SHELLPACK parseargParam    --iterations   LINKBENCH_ITERATIONS
###SHELLPACK parseargEnd

###SHELLPACK check_install_required linkbench-${VERSION}

###SHELLPACK monitor_hooks

if [ ! -e $JAVA_HOME ]; then
	install-depends java-1_7_0-openjdk
	install-depends java-1_7_0-openjdk-devel

	if [ ! -e /usr/lib64/jvm/java ]; then
		echo ERROR: Java binary is not located at $JAVA_HOME as configured
		exit -1
	fi
	export JAVA_HOME=/usr/lib64/jvm
fi
export PATH=$JAVA_HOME:$JAVA_HOME/bin:$PATH

CONFIG_PATH=$SHELLPACK_SOURCES/linkbench-${VERSION}-installed/config/

###SHELLPACK threads_large_stride_begin $LINKBENCH_MIN_THREADS $LINKBENCH_MAX_THREADS
		monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
		mmtests_activity $NR_THREADS

		###SHELLPACK iteration_begin $LINKBENCH_ITERATIONS
				$SHELLPACK_INCLUDE/shellpack-bench-mariadbbuild --start \
				    --start_opts $DBSTART_OPTIONS \
				    --effective_cachesize $((MEMTOTAL_BYTES*6/10)) \
				    --shared_buffers $((MEMTOTAL_BYTES/4)) \
				    --work_mem $((16*1048576)) || die Failed to get usable database installation

				# This is the data-request phase.
				echo Starting request run $ITERATION/$LINKBENCH_ITERATIONS, $NR_THREADS requester threads.
				echo Performing $LINKBENCH_WARMUP_TIME second warmup phase

				$SHELLPACK_SOURCES/linkbench-${VERSION}-installed/bin/linkbench -c $CONFIG_PATH/MyConfig.properties \
				    -D warmup_time=$LINKBENCH_WARMUP_TIME \
				    -D requesters=$NR_THREADS \
				    -L $LOGDIR_RESULTS/linkbench-request-${NR_THREADS}-${ITERATION}.log -r

				$SHELLPACK_INCLUDE/shellpack-bench-mariadbbuild --stop

		###SHELLPACK iteration_end $ITERATIONS
		monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
###SHELLPACK threads_stride_end

exit $SHELLPACK_SUCCESS
