#!/bin/bash
#
###SHELLPACK preamble timeexit-bench 0
DELAY=1
INSTANCES=$NUMCPUS
ITERATIONS=120

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam -d DELAY
###SHELLPACK parseargParam -c INSTANCES
###SHELLPACK parseargParam -i ITERATIONS
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK check_install_required timeexit

pushd $SHELLPACK_SOURCES/timeexit-${VERSION}-installed > /dev/null
monitor_pre_hook $LOGDIR_RESULTS $P
for ITERATION in `seq 1 $ITERATIONS`; do
	echo -n "$INSTANCES " | tee -a $LOGDIR_RESULTS/timeexit.log
	save_rc ./timeexit -p $DELAY $INSTANCES | tee -a $LOGDIR_RESULTS/timeexit.log
	recover_rc
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
		echo Error encountered in hackbench
		exit $SHELLPACK_ERROR
	fi
done
monitor_post_hook $LOGDIR_RESULTS $P

exit $RETVAL
