#!/bin/bash
# sqlite installer
###SHELLPACK preamble sqlite-install 3340000
WEB_LOCATION=https://www.sqlite.org/2020
MIRROR_LOCATION="$WEBROOT/sqlite/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch sqlite-autoconf-${VERSION}.tar.gz sqlite-${VERSION}

# Build
###SHELLPACK build_start sqlite-${VERSION}
###SHELLPACK build_configure sqlite-${VERSION}
###SHELLPACK make_make_install

###SHELLPACK self_extract sqlite-txnpersec.pl
chmod a+x $SHELLPACK_TEMP/sqlite-txnpersec.pl
mv $SHELLPACK_TEMP/sqlite-txnpersec.pl $SHELLPACK_SOURCES/sqlite-${VERSION}-installed/bin || die "Failed to relocate transction processing script"

echo sqlite installed successfully
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file sqlite-txnpersec.pl
