$SHELLPACK_TOPLEVEL/shellpack_src/src/refresh.sh postgresbuild

run_bench() {
	PGBENCH_MAX_TIME_COMMAND=
	PGBENCH_MAX_TRANSACTIONS_COMMAND=
	PGBENCH_SCALE_COMMAND=
	PGBENCH_MINTHREAD_COMMAND=

	if [ "$PGBENCH_MIN_CLIENTS" != "" ]; then
		PGBENCH_MINTHREAD_COMMAND="--min-threads $PGBENCH_MIN_CLIENTS"
	fi
	if [ "$PGBENCH_MAX_TIME" != "" ]; then
		PGBENCH_MAX_TIME_COMMAND="--max-time $PGBENCH_MAX_TIME"
		PGBENCH_MAX_TRANSACTIONS_COMMAND=
	fi
	if [ "$PGBENCH_SCALE_FACTOR" != "" ]; then
		PGBENCH_SCALE_COMMAND="--scale-factor $PGBENCH_SCALE_FACTOR"
	fi

	$SHELLPACK_INCLUDE/shellpack-bench-pgbench \
		${PGBENCH_MAX_TIME:+--max-time $PGBENCH_MAX_TIME}			\
		${PGBENCH_MIN_CLIENTS:+--min-clients $PGBENCH_MIN_CLIENTS}		\
		${PGBENCH_MAX_CLIENTS:+--max-clients $PGBENCH_MAX_CLIENTS}		\
		${PGBENCH_SCALE_FACTOR:+--scale-factor $PGBENCH_SCALE_FACTOR}		\
		${PGBENCH_LOADSCRIPT:+--loadscript $PGBENCH_LOADSCRIPT}			\
		${POSTGRESQL_SHAREDBUFFERS:+--shared-buffers $POSTGRESQL_SHAREDBUFFERS}	\
		${POSTGRESQL_CACHESIZE:+--effective-cachesize $POSTGRESQL_CACHESIZE}
	return $?
}
