#!/bin/bash
###SHELLPACK preamble wrf-bench 3.8.1
###SHELLPACK parseargBegin
###SHELLPACK parseargParam --model	WRF_MODEL
###SHELLPACK parseargParam --max-cpus   WRF_MAXCPUS
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

install-depends gcc gcc-fortran
install-depends netcdf-devel netcdf-fortran-devel hdf5-devel
install-depends curl libcurl-devel

MIRROR_LOCATION="$WEBROOT/wrf"
NETCDFC_VERSION=v4.7.3
NETCDFFC_VERSION=v4.5.2

###SHELLPACK mpi_setup_deps WRF_OPENMPI_VERSION
###SHELLPACK mpi_setup_env WRF_OPENMPI_VERSION WRF_MPI_PATH WRF_MPI_LIBPATH WRF_MPI_OPTS
###SHELLPACK mpi_setup_shmem

###SHELLPACK install_clear netcdf-installed
###SHELLPACK check_external_install_required_continue netcdfcbuild netcdfcbuild-$NETCDFC_VERSION $NETCDFC_VERSION
###SHELLPACK install_merge netcdfcbuild-$NETCDFC_VERSION netcdf-installed
###SHELLPACK check_external_install_required_continue netcdffcbuild netcdffcbuild-$NETCDFFC_VERSION $NETCDFFC_VERSION
###SHELLPACK install_merge netcdffcbuild-$NETCDFFC_VERSION netcdf-installed
###SHELLPACK check_install_required wrf-$VERSION
export LD_LIBRARY_PATH=$SHELLPACK_SOURCES/netcdf-installed/lib:$LD_LIBRARY_PATH

case $WRF_MODEL in
conus12km)
	if [ ! -e $SHELLPACK_SOURCES/wrf-$VERSION-installed/test/em_real_bench ]; then
		cd $SHELLPACK_SOURCES/wrf-$VERSION-installed/test || die "Failed to change to test directory"
		file_fetch UNAVAILABLE/conus12km_data_v3.tar.xz $MIRROR_LOCATION/conus12km_data_v3.tar.xz conus12km_data_v3.tar.xz
		cp -r em_real em_real_bench
		tar -xf conus12km_data_v3.tar.xz || die "Failed to extract conus12km"
	fi
	;;
*)
	die "Unrecognised model $WRF_MODEL"
esac
###SHELLPACK init_complete

BENCH_CMD="mpirun $WRF_MPI_OPTS $MMTESTS_MPI_OPTS -np $WRF_MAXCPUS ./wrf.exe"
monitor_pre_hook $LOGDIR_RESULTS $SPECFEM3D_MODEL
case $WRF_MODEL in
conus12km)
	cd $SHELLPACK_SOURCES/wrf-$VERSION-installed/test/em_real_bench
	save_rc $TIME_CMD -o $LOGDIR_RESULTS/wrf-time.$WRF_MODEL   \
		$BENCH_CMD 2>&1 | tee $LOGDIR_RESULTS/wrf-log.$WRF_MODEL
	recover_rc
	if [ $? -ne 0 ]; then
		die "Failed to execute $WRF_MODEL"
	fi
	;;
*)
	die "Unrecognised model $WRF_MODEL"
esac
monitor_post_hook $LOGDIR_RESULTS $SPECFEM3D_MODEL
