#!/bin/bash
# $1:	field
# $2	test
# $3:	timestamp file

if [ "$1" = "" ] ; then
	echo Usage: tests-timestamp-extract FIELD TESTNAME file
	exit -1
fi

FIELD_PATTERN=$1
FTRACE_TEST=$2
INPUT=$3

if [ ! -e "$INPUT" ]; then
	echo Timestamp file does not exist
	exit -1
fi

# Extract information from tests-timestamp
TESTSTART=`grep -n "test begin :: $FTRACE_TEST" $INPUT | awk -F : '{print $1}'`
TESTEND=`grep -n "test end :: $FTRACE_TEST" $INPUT | awk -F : '{print $1}'`
TESTLENGTH=$(($TESTEND-$TESTSTART))
head -$TESTEND $INPUT | tail -$TESTLENGTH > /tmp/vmstat.txt

# Get the full list of fields
FIELDS=`grep "$FIELD_PATTERN" $INPUT | awk '{print $1}' | sort | uniq`

VALUE=0
for FIELD in $FIELDS; do

	VALUESTART=`grep "^$FIELD " /tmp/vmstat.txt | awk '{print $2}' | head -1`
	VALUEEND=`grep "^$FIELD " /tmp/vmstat.txt | awk '{print $2}' | tail -1`

	VALUE=$(($VALUE+$VALUEEND-$VALUESTART))
done

echo $VALUE
