#!/bin/bash

###SHELLPACK preamble perfbuild-install 5.15
WEB_LOCATION="https://www.kernel.org/pub/linux/kernel/v5.x"
MIRROR_LOCATION="$WEBROOT/linux/"

install-depends python3-devel
install-depends bison
install-depends flex
install-depends libdw-devel
install-depends libfdata-devel
install-depends libnuma-devel
install-depends python-devel
install-depends libzstd-devel
install-depends libunwind-devel
install-depends zlib-devel-static

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch linux-${VERSION}.tar.xz perfbuild-${VERSION}
###SHELLPACK build_start perfbuild-${VERSION}

###SHELLPACK build_start perfbuild-${VERSION}/tools/perf
sed -i -e s/-DHAVE_LIBBFD_SUPPORT// Makefile.config
###SHELLPACK make NO_LIBBFD=1 prefix=$SHELLPACK_SOURCES/perfbuild-${VERSION}-installed
###SHELLPACK make NO_LIBBFD=1 prefix=$SHELLPACK_SOURCES/perfbuild-${VERSION}-installed install

exit $SHELLPACK_SUCCESS
