#!/bin/bash
###SHELLPACK preamble preaddd-bench 0
SRCTAR=
SRCTAR_EXTRA=
TARGETSIZE_MB=
NUMCPUS=$(grep -c '^processor' /proc/cpuinfo)
ITERATIONS=5
CONV=

###SHELLPACK parseargBegin
###SHELLPACK parseargParam --min-instances	INSTANCES
###SHELLPACK parseargParam --iterations   	ITERATIONS
###SHELLPACK parseargParam --targetsize		TOTAL_FILESIZE
###SHELLPACK parseargEnd

###SHELLPACK monitor_hooks

cd $TESTDISK_DIR || die Failed to change to temp directory
FILESIZE=$((TOTAL_FILESIZE/INSTANCES))

echo Creating source files
echo o Total filesize $TOTAL_FILESIZE MB
echo o Process filesize $FILESIZE MB
for i in `seq 1 $INSTANCES`; do
	dd if=/dev/zero of=zerofile-$i ibs=4096 count=$((FILESIZE*1048576/4096)) 2>&1 &
	wait
done

sync
echo Reading files back
monitor_pre_hook $LOGDIR_RESULTS $INSTANCES
for ITERATION in `seq 1 $ITERATIONS`; do
	for i in `seq 1 $INSTANCES`; do
		dd if=zerofile-$i of=/dev/null 2>&1 | tee -a $LOGDIR_RESULTS/dd.$ITERATION-$i &
	done
	wait
done
monitor_post_hook $LOGDIR_RESULTS $INSTANCES
rm zerofile-*

exit $SHELLPACK_SUCCESS
