#!/bin/bash
###SHELLPACK preamble revocapbuild revocap-1.1.04

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargBindings
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

export REVOCAP_VERSION="1.1.04"
# dependencies
###SHELLPACK check_external_install_required revocapbuild   revocapbuild-${REVOCAP_VERSION} ${REVOCAP_VERSION}
