#!/bin/bash

###SHELLPACK preamble pgbench-bench 9.2.1

ROLE=`whoami`
DBUSER=nobody
DBPASSWORD=shellpack-mysqlbench
EFFECTIVE_CACHESIZE=$((756*1048576))
SHARED_BUFFERS=$((32*1048576))
WORK_MEM=$((32*1048576))
MAX_TIME=
MAX_TRANSACTIONS=
MAX_ITERATIONS=5
READONLY_ARG=
SCALE_FACTOR=1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam --max-threads         PGBENCH_MAX_THREADS
###SHELLPACK parseargParam --effective-cachesize EFFECTIVE_CACHESIZE
###SHELLPACK parseargParam --scale-factor        SCALE_FACTOR
###SHELLPACK parseargParam --shared-buffers      SHARED_BUFFERS
###SHELLPACK parseargParam --work-mem            WORK_MEM
###SHELLPACK parseargParam --max-time            MAX_TIME
###SHELLPACK parseargParam --max-transactions    MAX_TRANSACTIONS
###SHELLPACK parseargParam --iterations          MAX_ITERATIONS
###SHELLPACK parseargYes   --read-only           READONLY
	--use-large-pages)
		export LARGEPAGES=--use-large-pages
		shift
		;;
	--use-dynamic-pool)
		export USE_DYNAMIC_POOL=--use-dynamic-pool
		shift
		;;
###SHELLPACK parseargEnd

if [ "$MAX_TIME" != "" ]; then
	MAX_TIME="-T $MAX_TIME"
else
	if [ "$MAX_TRANSACTIONS" != "" ]; then
		MAX_TRANSACTIONS="-t $MAX_TRANSACTIONS"
	else
		die Specify time or transactions
	fi
fi

###SHELLPACK monitor_hooks

# Install if necessary and run database. Do not use large pages or google
# malloc as they are unnecessary at this point
$SHELLPACK_INCLUDE/shellpack-install-postgresbuild \
	-v ${VERSION} \
	--effective_cachesize $EFFECTIVE_CACHESIZE \
	--shared_buffers $SHARED_BUFFERS \
	--work_mem $WORK_MEM \
	|| die Failed to get a usable postgres installation
export PGHOST=/var/run/postgresql
export PGPORT=5432
export PATH=$SHELLPACK_SOURCES/postgres-${VERSION}-installed/bin:$PATH
export LD_LIBRARY_PATH=postgres-${VERSION}-installed/lib
if [ "$INSTALL_ONLY" = "yes" ]; then
	echo
	echo pgbench install-only successfully completed
	exit $SHELLPACK_SUCCESS
fi

echo Copying database configuration
cp $SHELLPACK_SOURCES/postgres-${VERSION}-installed/data/postgresql.conf $LOGDIR_RESULTS

# Calculate memory requirements
. $SHELLPACK_INCLUDE/include-hugepage.sh
gethugepagesize
UPPERLIMIT=$((`grep ^MemTotal /proc/meminfo  | awk '{print $2}'`*1024*3/4))
TOTALBUFFER_SIZE=$(($UPPERLIMIT+1))
while [ $TOTALBUFFER_SIZE -ge $UPPERLIMIT ]; do
	TOTALBUFFER_SIZE=$(($EFFECTIVE_CACHESIZE))

	if [ $TOTALBUFFER_SIZE -ge $UPPERLIMIT ]; then
		echo Shrinking memory requirements \($TOTALBUFFER_SIZE ge $UPPERLIMIT\)
		EFFECTIVE_CACHESIZE=$(($EFFECTIVE_CACHESIZE-$EFFECTIVE_CACHESIZE/10))
		SHARED_BUFFERS=$(($SHARED_BUFFERS-$SHARED_BUFFERS/10))
		WORK_MEM=$(($WORK_MEM-$WORK_MEM/10))
		KEYBUFFER_SIZE=$(($KEYBUFFER_SIZE-$KEYBUFFER_SIZE/10))
	fi
done

echo Shutting down DB to reconfigure system
$SHELLPACK_INCLUDE/shellpack-install-postgresbuild --shutdown

# Configure shmem parameters
getpagesize
echo $TOTALBUFFER_SIZE > /proc/sys/kernel/shmmax
echo $(($TOTALBUFFER_SIZE*2/$PAGESIZE)) > /proc/sys/kernel/shmall
ulimit -l $TOTALBUFFER_SIZE
GROUPNAME=`groups $POSTGRES_USER | awk '{print $3}'`
if [ "$GROUPNAME" = "" ]; then
	GROUPNAME=`groups $POSTGRES_USER`
fi
GROUPID=`grep ^$GROUPNAME: /etc/group | cut -d: -f3`
echo $GROUPID > /proc/sys/vm/hugetlb_shm_group

# Reserve the required hugepages if necessary
if [ "$LARGEPAGES" != "" ]; then
	# Reserve the hugepages
	REQUIRED_HUGEPAGES=$(($TOTALBUFFER_SIZE/$HUGE_PAGESIZE))
	echo Required hugepages: $REQUIRED_HUGEPAGES
	if [ $HUGE_PAGESIZE -gt 4194304 ]; then
		REQUIRED_HUGEPAGES=$(($REQUIRED_HUGEPAGES+$REQUIRED_HUGEPAGES/4))
		echo Adjusted for larger pages required hugepages: $REQUIRED_HUGEPAGES
	fi

	if [ $NUMCPUS -gt 32 ]; then
		REQUIRED_HUGEPAGES=$(($REQUIRED_HUGEPAGES*4))
		echo Adjusted for number cpus required hugepages: $REQUIRED_HUGEPAGES
	fi
	reserve_hugepages $USE_DYNAMIC_POOL $REQUIRED_HUGEPAGES
fi

# Restart the database
echo Starting DB up after configuring system
$SHELLPACK_INCLUDE/shellpack-install-postgresbuild $LARGEPAGES \
	--effective_cachesize $EFFECTIVE_CACHESIZE \
	--shared_buffers $SHARED_BUFFERS \
	--work_mem $WORK_MEM \
	-v ${VERSION} \
	|| die Failed to get a usable mysql installation
export PGHOST=localhost
export PGPORT=5432

# Create database
echo Creating database
PSQL=$SHELLPACK_SOURCES/postgres-${VERSION}-installed/bin/psql
RUNDBUSER="su -s /bin/bash $DBUSER -c"

$PSQL "template1 -c 'CREATE DATABASE pgbench;'"
if [ $? -ne 0 ]; then
	echo " o Database create returned $?"
	echo " o Dumping previous runs database"
	$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgbench;'"
	echo " o Re-creating database"
	$RUNDBUSER "$PSQL template1 -c 'CREATE DATABASE pgbench;'" || die Failed to setup database
fi

$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE $ROLE with LOGIN;'"
if [ $? -ne 0 ]; then
	echo " o Role create returned $?"
	$RUNDBUSER "$PSQL template1 -c 'DROP ROLE $ROLE;'"
	$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE $ROLE with LOGIN;'" || die Failed to create $ROLE role
fi

# Figure out how to use the time command
TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

echo Initialising database for pgbench
$TIME_CMD pgbench -h $PGHOST -p $PGPORT -i pgbench -s $SCALE_FACTOR \
	2>> $LOGDIR_RESULTS/load.time | tee $LOGDIR_RESULTS/load.log

if [ "$READONLY" = "yes" ]; then
	READONLY_ARG=-S
fi

echo Running pgbench maximum $PGBENCH_MAX_THREADS threads
###SHELLPACK threads_stride_begin 1 $PGBENCH_MAX_THREADS
	echo -n > $LOGDIR_RESULTS/samples
	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
	for ITER in `seq 1 $MAX_ITERATIONS`; do
		echo -n o $NR_THREADS threads iter $ITER
		$TIME_CMD -o $LOGDIR_RESULTS/time-$NR_THREADS.$ITER \
			pgbench -v -h $PGHOST -p $PGPORT \
				$READONLY_ARG -c $NR_THREADS \
				$MAX_TRANSACTIONS $MAX_TIME \
				pgbench > $LOGDIR_RESULTS/pgbench-raw-$NR_THREADS-$ITER
		SYSRET=$?
		if [ $SYSRET -ne 0 ]; then
			cat $LOGDIR_RESULTS/pgbench-raw-$NR_THREADS-$ITER
			die pgbench failed to execute
		fi
	done
	monitor_post_hook $LOGDIR_RESULTS $NR_THRADS
###SHELLPACK threads_stride_end

# Copy the log files
cp $SHELLPACK_SOURCES/postgres-${VERSION}-installed/logfile $LOGDIR_RESULTS/dblog

$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgbench;'"

# Shutdown server
$SHELLPACK_INCLUDE/shellpack-install-postgresbuild --shutdown
reset_hugepages

echo pgbench successfully completed
exit $SHELLPACK_SUCCESS
