#!/bin/bash
###SHELLPACK preamble xfstests-install 20110701
GIT_LOCATION=git://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git
MIRROR_LOCATION="$WEBROOT/xfstests/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

# TODO: more install-depends
install-depends libuuid-devel

###SHELLPACK git_fetch xfstests-${VERSION}.tar.gz xfstests-${VERSION}-installed

# Edit some of the tests
sed -i -e 's/$i -lt 1000/$i -lt $XFSTESTS_180_NR_FILES/' 180.tmp

###SHELLPACK build_start xfstests-${VERSION}-installed
###SHELLPACK make

echo xfstests installed successfully
exit $SHELLPACK_SUCCESS
