#!/bin/bash
# Run the regression tests

###SHELLPACK preamble xfstests-bench 20110701

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK check_install_required xfstests-${VERSION}
###SHELLPACK monitor_hooks

# Check configuration
if [ "$XFSTESTS_TEST_DEV" = "" ]; then
	die XFSTESTS_TEST_DEV must be configured
fi
if [ "$XFSTESTS_SCRATCH_DEV" = "" ]; then
	die XFSTESTS_SCRATCH_DEV must be configured
fi
if [ "$TESTDISK_FILESYSTEM" = "" ]; then
	die TESTDISK_FILESYSTEM must be configured
fi

# Configure environment
export TEST_DEV=$XFSTESTS_TEST_DEV
export TEST_DIR=$SHELLPACK_TEMP/test_dir
export SCRATCH_DEV=$XFSTESTS_SCRATCH_DEV
export SCRATCH_MNT=$SHELLPACK_TEMP/scrach_mnt
export FSTYP=$TESTDISK_FILESYSTEM

mkdir -p $TEST_DIR
mkdir -p $SCRATCH_MNT

monitor_pre_hook $LOGDIR_RESULTS default

./check -T 2>&1 | tee $LOGDIR_RESULTS/xfstests-default.log \
	|| die Failed to run xfstests

monitor_post_hook $LOGDIR_RESULTS $SIZE

exit $SHELLPACK_SUCCESS
