#!/bin/bash

###SHELLPACK preamble specjvm-install 2005_kitv1.07
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/proprietary/spec"

for PACKAGE in $SPECJBB_PACKAGES; do
        install-depends $PACKAGE
done

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch SPECjbb${VERSION}.tar.gz specjbb-${VERSION}-installed

exit $SHELLPACK_SUCCESS
