#!/bin/bash

FSCONFIGS="
config-global-dhp__io-threaded
config-global-dhp__io-threaded-fixed
config-global-dhp__io-metadata
config-global-dhp__io-dbench4-async
config-global-dhp__io-dbench4-fsync
config-global-dhp__io-mailserver
config-global-dhp__io-sysbench-large-rw
config-global-dhp__io-sysbench-large-ro
config-global-dhp__io-gitcheckout-performance
config-global-dhp__io-gitcheckout-read-starvation
config-global-dhp__io-gitcheckout-randread-starvation
config-global-dhp__io-gitcheckout-write-starvation
config-global-dhp__io-gitcheckout-randwrite-starvation
config-global-dhp__pagereclaim-performance
config-global-dhp__reaim-alltests
config-global-dhp__reaim-stress-alltests
config-global-dhp__stress-highalloc-performance
config-global-dhp__io-interactive-performance
config-global-dhp__io-largeread-starvation
config-global-dhp__io-randread-starvation
config-global-dhp__background-highalloc-thp-performance
config-global-dhp__background-highalloc-hugetlbfs-performance
config-global-dhp__parallelio-memcachetest
"
for CONFIG in $FSCONFIGS; do
	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=ext3/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM=/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=barrier=0/' \
			> $CONFIG-ext3

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=ext4/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM=/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=/' \
			> $CONFIG-ext4

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=btrfs/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM="-f"/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=/' \
			> $CONFIG-btrfs

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=xfs/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM="-f -d agcount=8"/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=inode64,delaylog,logbsize=262144,nobarrier/' \
			> $CONFIG-xfs

done

LIMITMEM_CONFIGS="
config-global-dhp__largecopytar-performance
"
for CONFIG in $LIMITMEM_CONFIGS; do
	DESTCONFIG=`echo $CONFIG | sed -e 's/dhp__/dhp-2048M__/'`

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=ext3/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM=/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=barrier=0/' \
			> $DESTCONFIG-ext3

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=ext4/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM=/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=/' \
			> $DESTCONFIG-ext4

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=btrfs/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM="-f"/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=/' \
			> $DESTCONFIG-btrfs

	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=\/dev\/sda6/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=xfs/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM="-f -d agcount=8"/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=inode64,delaylog,logbsize=262144,nobarrier/' \
			> $DESTCONFIG-xfs
done

TMPFS_CONFIGS="
"

for CONFIG in $TMPFS_CONFIGS; do
	cat $CONFIG | sed \
		-e 's/.*export TESTDISK_PARTITION.*/export TESTDISK_PARTITION=none/' \
		-e 's/.*export TESTDISK_FILESYSTEM=.*/export TESTDISK_FILESYSTEM=tmpfs/' \
		-e 's/.*export TESTDISK_MKFS_PARAM=.*/export TESTDISK_MKFS_PARAM=/' \
		-e 's/.*export TESTDISK_MOUNT_ARGS=.*/export TESTDISK_MOUNT_ARGS=/' \
			> $CONFIG-tmpfs
done
