#!/bin/bash

###SHELLPACK preamble bonnie-install 1.03e
WEB_LOCATION="http://www.coker.com.au/bonnie++"
MIRROR_LOCATION="$WEBROOT/bonnie"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

rm -rf $SHELLPACK_SOURCES/bonnie-${VERSION}
###SHELLPACK sources_fetch bonnie%2B%2B-${VERSION}.tgz bonnie-$VERSION

###SHELLPACK build_start bonnie-$VERSION
###SHELLPACK build_configure bonnie-${VERSION}
###SHELLPACK make_make_install

exit $SHELLPACK_SUCCESS
