#!/bin/bash
# libmicro installer
###SHELLPACK preamble libmicro-smallbatches-install 1
GIT_LOCATION=https://github.com/redhat-performance/libMicro
MIRROR_LOCATION="$WEBROOT/libmicro"

install-depends gcc

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch libmicro-smallbatches-${VERSION}.tar.gz libmicro-smallbatches-${VERSION}-installed

###SHELLPACK build_start libmicro-smallbatches-${VERSION}-installed
sed -i -e 's/tattle.c libmicro.a -lrt -lm.*/tattle.c libmicro.a -lrt -lm -lpthread/' Makefile.com

###SHELLPACK make_clean
###SHELLPACK make

echo libmicro installed successfully
