#!/bin/bash
###SHELLPACK preamble openmpibuild v3.1.6
GIT_LOCATION=https://github.com/open-mpi/ompi
MIRROR_LOCATION="$WEBROOT/openmpi/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

[ $(uname -m) = x86_64 ] && install-depends libpsm2-devel

###SHELLPACK git_fetch openmpibuild-${VERSION}.tar.gz openmpibuild-${VERSION}
###SHELLPACK build_start openmpibuild-${VERSION}

CONFIGURE_FLAGS="--enable-builtin-atomics --enable-mpi-thread-multiple --disable-silent-rules --enable-mpirun-prefix-by-default --with-package-string=\"MMTests Self Build OpenMPI\""

case `uname -m` in
x86_64)
	CONFIGURE_FLAGS+=" --with-psm2"
	;;
esac

./autogen.pl || die "Failed autogen.pl"
###SHELLPACK build_configure openmpibuild-${VERSION} $CONFIGURE_FLAGS
###SHELLPACK make_make_install

echo openmpi installed successfully
