#!/bin/bash

###SHELLPACK preamble aim9-install 9110
WEB_LOCATION="http://heanet.dl.sourceforge.net/sourceforge/aimbench"
MIRROR_LOCATION="$WEBROOT/aim9"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch s${VERSION}.tar.Z aim9-$VERSION-installed

###SHELLPACK build_start aim9-$VERSION-installed
echo  > aim9.configure
echo >> aim9.configure
echo >> aim9.configure
echo >> aim9.configure
echo >> aim9.configure

cat aim9.configure | ./S9setup || die Failed to configure aim9

###SHELLPACK make
cp s9workfile s9workfile-full
echo "# @(#) s9workfile:1.2 1/22/96 00:00:00
# AIM Independent Resource Benchmark - Suite IX Workfile
FILESIZE: 5M >> s9workfile-short
page_test
brk_test
exec_test
fork_test" >> s9workfile-short

exit $SHELLPACK_SUCCESS
