#!/bin/bash

###SHELLPACK preamble futexbench-install 3.16.3
WEB_LOCATION="https://www.kernel.org/pub/linux/kernel/v3.x"
MIRROR_LOCATION="$WEBROOT/linux/"

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch linux-${VERSION}.tar.xz futexbench-${VERSION}-installed
###SHELLPACK build_start futexbench-${VERSION}-installed/tools/perf
###SHELLPACK make

exit $SHELLPACK_SUCCESS
