#!/bin/bash
# Run perf-bench futex benchmark

###SHELLPACK preamble futexbench-bench 3.16.3
TESTTIME=15
ITERATIONS=12
TESTLIST=
MAX_THREADS=$NUMCPUS

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam   --min-threads      FUTEXBENCH_MIN_THREADS
###SHELLPACK parseargParam   --max-threads      FUTEXBENCH_MAX_THREADS
###SHELLPACK parseargParam   --workloads	FUTEXBENCH_WORKLOADS
###SHELLPACK parseargEnd

###SHELLPACK check_install_required futexbench-${VERSION}

# Include monitor hooks
. $SHELLPACK_INCLUDE/include-monitor.sh

PERF_DIR=$SHELLPACK_SOURCES/futexbench-${VERSION}-installed/tools/perf/
PERF_CMD=${PERF_DIR}/perf

echo $FUTEXBENCH_WORKLOADS > $LOGDIR_RESULTS/workloads

###SHELLPACK threads_stride_begin $FUTEXBENCH_MIN_THREADS $FUTEXBENCH_MAX_THREADS
	for WORKLOAD in $FUTEXBENCH_WORKLOADS; do
		mmtests_activity $WORKLOAD-$NR_THREADS
		echo Running test $WORKLOAD
		monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
		$PERF_CMD bench futex $WORKLOAD -t $NR_THREADS 2>&1 | \
			tee $LOGDIR_RESULTS/$WORKLOAD-${NR_THREADS}.log \
			|| die Failed ro run perf-bench futex
		monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
	done
###SHELLPACK threads_stride_end

exit $SHELLPACK_SUCCESS
