#!/bin/bash

###SHELLPACK preamble specjvm 2008
WEB_LOCATION="NOT_AVAILABLE"
MIRROR_LOCATION="$WEBROOT/proprietary/spec/SPECjvm2008_1_00_setup.jar"

for PACKAGE in $SPECJVM_PACKAGES; do
	install-depends $PACKAGE
done

cd $SHELLPACK_SOURCES || die "Sources directory does not exist"
sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/SPECjvm2008_1_00_setup.jar
java -jar SPECjvm2008_1_00_setup.jar -DUSER_INSTALL_DIR=`pwd`/specjvm -i silent || die "Failed to install specjvm"

exit $SHELLPACK_SUCCESS
