#!/bin/bash
# LTP installer
###SHELLPACK preamble ltp-install 20200515
GIT_LOCATION=https://github.com/linux-test-project/ltp
MIRROR_LOCATION="$WEBROOT/ltp"

install-depends mkisofs

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK git_fetch ltp-${VERSION}.tar.gz ltp-$VERSION
###SHELLPACK build_start ltp-${VERSION}
make autotools || die "Failed to make autotools"
sed -i -e 's/read ans/ans=y/' IDcheck.sh
###SHELLPACK build_configure ltp-${VERSION}
###SHELLPACK make_make_install

echo LTP installed successfully
