#!/bin/bash
# LTP installer
P=ltp-install
INSTALL_TESTS=0
VERSION=
DEFAULT_VERSION=20150420
WEB_LOCATION=http://heanet.dl.sourceforge.net/sourceforge/ltp
MIRROR_LOCATION=$WEBROOT/ltp
LTP_SOURCE_REPO=http://mcp/mmtests-mirror
. $SHELLPACK_INCLUDE/common.sh

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK sources_fetch ltp-full-${VERSION}.tar.bz2 ltp-$VERSION
###SHELLPACK build_start ltp-$VERSION
###SHELLPACK build_configure ltp-${VERSION}
###SHELLPACK make_make_install

echo LTP installed successfully
