#!/bin/bash
# This script installs ltp and runs the regression tests
###SHELLPACK preamble ltp-bench 20190115
LTP_RUN_TESTS="controllers"
LTP_RUN_ITERATIONS=1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam --ltp-tests LTP_RUN_TESTS
###SHELLPACK parseargParam --ltp-args LTP_RUN_ARGS
###SHELLPACK parseargParam --ltp-iterations LTP_RUN_ITERATIONS
###SHELLPACK parseargEnd

###SHELLPACK check_install_required ltp-${VERSION}

# Run the testsuite
cd $SHELLPACK_SOURCES/ltp-${VERSION}-installed || die "Failed to cd to ltp install directory"
export PATH=$PATH:$SHELLPACK_SOURCES/ltp-${VERSION}-installed/testcases/bin

for TESTNAME in $LTP_RUN_TESTS; do
	echo Executing $TEST LTP test
	RESULTS="$LOGDIR_RESULTS"

	for ITER in `seq 1 $LTP_RUN_ITERATIONS`; do
		if [ "$TESTNAME" = "test-direct-process" ]; then
			# This is part of a CPU hotplug reproduction case. It hammers
			# process creation and is intended as a scheduler stress test
			save_rc ./testcases/bin/process -b 10 -d 5 | tee $LOGDIR_RESULTS/ltp-${TESTNAME}.log
		elif [ -e runtest/$TESTNAME ]; then
			save_rc ./runltp -f $TESTNAME $LTP_RUN_ARGS  | tee $LOGDIR_RESULTS/ltp-${TESTNAME}.log
		elif [ -e testcases/bin/$TESTNAME ]; then
			save_rc ./testcases/bin/$TESTNAME $LTP_RUN_ARGS | tee $LOGDIR_RESULTS/ltp-${TESTNAME}.log
		else
			die "No method available to run $TESTNAME"
		fi
		recover_rc
		echo $? > $LOGDIR_RESULTS/${TESTNAME}.status
	done

	# Check for failures
	#grep -v PASS $RESULTS/log-$TEST.txt > $RESULTS/failed_tests.txt
	#TEST=`cat $RESULTS/failed_tests.txt`
	#if [ "$TEST" != "" ]; then
	#	echo
	#	echo Some ltp regression tests reported failure | tee -a $LOGDIR/summary
	#	cat $RESULTS/failed_tests.txt | tee -a $LOGDIR/summary
	#	echo
	#
	#	echo ltp successfully installed but some regression tests failed | tee -a $LOGDIR/summary
	#	exit $SHELLPACK_ERROR
	#fi
done

echo
exit $SHELLPACK_SUCCESS
