#!/bin/bash
###SHELLPACK preamble cyclictest-install 0
GIT_LOCATION=git://git.kernel.org/pub/scm/linux/kernel/git/clrkwllms/rt-tests.git
MIRROR_LOCATION="$WEBROOT/cyclictest/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch cyclictest-${VERSION}.tar.gz cyclictest-${VERSION}-installed

install-depends libnuma-devel

###SHELLPACK build_start cyclictest-${VERSION}-installed
###SHELLPACK make

echo cyclictest installed successfully
