#!/usr/bin/perl -wn
# Print out the quartiles of data read from standard in

use FindBin qw($Bin);
use lib "$Bin/lib/";
use MMTests::Stat;

$x[$i++] = $_;
END {
	$i = 0;
	$quartiles = calc_quartiles(\@x);
	#$mean = calc_amean(\@x);
	#$stddev = calc_stddev("amean", \@x);
	#$range = $$quartiles[3] - $$quartiles[1];
	#print "$$quartiles[1] $$quartiles[2] $$quartiles[3]";
	print "$$quartiles[90] $$quartiles[93] $$quartiles[95] $$quartiles[99]";
}
