#!/bin/bash
###SHELLPACK preamble simoop-install 18929ada
GIT_LOCATION=git://git.kernel.org/pub/scm/linux/kernel/git/mason/simoop.git
MIRROR_LOCATION="$WEBROOT/extra/simoop/"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch simoop-${VERSION}.tar.gz simoop-${VERSION}-installed

###SHELLPACK build_start simoop-${VERSION}-installed
###SHELLPACK self_extract fix-overrun.patch
###SHELLPACK make

echo simoop installed successfully
exit $SHELLPACK_SUCCESS
