#!/bin/bash
# Run wis benchmark

###SHELLPACK preamble wis-bench a34a85cc1e9b
TESTTIME=15
ITERATIONS=12

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam	--min-threads	WIS_MIN_THREADS
###SHELLPACK parseargParam	--max-threads	WIS_MAX_THREADS
###SHELLPACK parseargParam	--workloads     WIS_WORKLOADS
###SHELLPACK parseargParam	--iterations    WIS_ITERATIONS
###SHELLPACK parseargParam	--models        WIS_MODELS
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK check_install_required wis-${VERSION}
###SHELLPACK init_complete

echo $WIS_WORKLOADS > $LOGDIR_RESULTS/workloads
echo $WIS_MODELS > $LOGDIR_RESULTS/models

IFS=',' read -a ALL_MODELS <<< "$WIS_MODELS"
IFS=',' read -a ALL_WORKLOADS <<< "$WIS_WORKLOADS"

for WORKLOAD in ${ALL_WORKLOADS[@]}
do
	###SHELLPACK threads_large_stride_begin $WIS_MIN_THREADS $WIS_MAX_THREADS
		monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
		for MODEL in ${ALL_MODELS[@]}; do
			echo Starting $WORKLOAD-$MODEL $NR_THREADS/$WIS_MAX_THREADS
			CMD="${WORKLOAD}_${MODEL}"
			$TIME_CMD -o $LOGDIR_RESULTS/time-$CMD-$NR_THREADS \
				./$CMD -t $NR_THREADS -s $WIS_ITERATIONS	\
					> $LOGDIR_RESULTS/benchlog-$CMD-$NR_THREADS

			# Get rid of the warmup values (number of runs are constant).
			sed -i '1,8d' $LOGDIR_RESULTS/benchlog-$CMD-$NR_THREADS
		done
		monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
	###SHELLPACK threads_stride_end
done

exit $SHELLPACK_SUCCESS
