#!/bin/bash
###SHELLPACK preamble hpagealloc-bench 0

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam	--pagesize	HPAGEALLOC_PAGESIZE
###SHELLPACK parseargParam	--nr		HPAGEALLOC_NR
###SHELLPACK parseargParam	--stride	HPAGEALLOC_STRIDE
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

###SHELLPACK check_install_required hpagealloc-${VERSION}
###SHELLPACK init_complete

monitor_pre_hook $LOGDIR_RESULTS $PAGESIZE
echo Starting $HPAGEALLOC_NR allocations of page size $((HPAGEALLOC_PAGESIZE/1048576))MB
echo $((HPAGEALLOC_PAGESIZE/1048576)) > $LOGDIR_RESULTS/hpagealloc.pagesize
$TIME_CMD -o $LOGDIR_RESULTS/hpagealloc.time							  \
	./bin/timed-hpagealloc.pl $HPAGEALLOC_NR $HPAGEALLOC_STRIDE $((HPAGEALLOC_PAGESIZE/1024)) \
			| tee $LOGDIR_RESULTS/hpagealloc.log
gzip -f $LOGDIR_RESULTS/hpagealloc.log

exit $SHELLPACK_SUCCESS
