#!/bin/bash
###SHELLPACK preamble hpagealloc 0

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK self_extract timed-hpagealloc.pl
install-depends perl-File-Slurp

mkdir -p $SHELLPACK_SOURCES/hpagealloc-${VERSION}-installed/bin
mv $SHELLPACK_TEMP/timed-hpagealloc.pl $SHELLPACK_SOURCES/hpagealloc-${VERSION}-installed/bin
chmod a+x $SHELLPACK_SOURCES/hpagealloc-${VERSION}-installed/bin/timed-hpagealloc.pl

echo hpagealloc installed successfully
exit $SHELLPACK_SUCCESS

###SHELLPACK include_file timed-hpagealloc.pl
