#!/bin/bash
###SHELLPACK preamble pnetcdfbuild pnetcdf-1.12.1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargBindings
###SHELLPACK parseargEnd
###SHELLPACK monitor_hooks

export PNETCDF_VERSION="1.12.1"
# dependencies
###SHELLPACK check_external_install_required pnetcdfbuild pnetcdfbuild-$PNETCDF_VERSION $PNETCDF_VERSION
