#!/bin/bash
###SHELLPACK preamble swappiness-bench 0

###SHELLPACK parseargBegin
###SHELLPACK parseargParam	--size			WORKLOAD_SIZE
###SHELLPACK parseargParam	--anon-size		PERCENTAGE_ANON
###SHELLPACK parseargParam	--min-swappiness	MIN_SWAPPINESS
###SHELLPACK parseargParam	--max-swappiness	MAX_SWAPPINESS
###SHELLPACK parseargParam	--steps			STEPS
###SHELLPACK parseargEnd

###SHELLPACK check_external_install_required usemembuild usemembuild-${VERSION}-installed ${VERSION}

function create_sparse_file() {
	dd if=/dev/zero of=$SHELLPACK_TEMP/$1 bs=32768 count=0 seek=$(($2/32768+1))
}

function create_populated_file() {
	dd if=/dev/zero of=$SHELLPACK_TEMP/$1 bs=32768 count=$(($2/32768+1))
}

ORIGINAL_SWAPPINESS=`cat /proc/sys/vm/swappiness`
MEMTOTAL_ANON=$((WORKLOAD_SIZE*PERCENTAGE_ANON/100))
MEMTOTAL_FILE=$((WORKLOAD_SIZE*(100-PERCENTAGE_ANON)/100))

echo Anon footprint $((MEMTOTAL_ANON/1048576))MB | tee $LOGDIR_RESULTS/anon-footprint
echo File footprint $((MEMTOTAL_FILE/1048576))MB | tee $LOGDIR_RESULTS/file-footprint
echo $ORIGINAL_SWAPPINESS > /proc/sys/vm/swappiness || die Failed to write swappiness
echo Creating file
create_populated_file workfile-1 $MEMTOTAL_FILE

USEMEM_LOOPS=50

###SHELLPACK threads_stride_fixed_begin $MIN_SWAPPINESS $MAX_SWAPPINESS $STEPS
	SWAPPINESS=$NR_THREADS

	mmtests_activity swappiness-$SWAPPINESS
	echo Executing test with swappiness $SWAPPINESS
	echo $SWAPPINESS > /proc/sys/vm/swappiness || die Failed to write swappiness

	unbuffer vmstat -n 1 > $LOGDIR_RESULTS/vmstat-$SWAPPINESS &
	PID_VMSTAT=$!

	echo "#!/bin/bash
	# File
	echo -n > $SHELLPACK_TEMP/usemem.pids
	$SHELLPACK_SOURCES/usemembuild-$VERSION-installed/usemem	\
		-f $SHELLPACK_TEMP/workfile-1				\
		-j 4096							\
		-r $USEMEM_LOOPS					\
		--readonly						\
		$MEMTOTAL_FILE 2> /dev/null &
	echo \$! >> $SHELLPACK_TEMP/usemem.pids

	# Anon
	$SHELLPACK_SOURCES/usemembuild-$VERSION-installed/usemem	\
		-j 4096							\
		-r $USEMEM_LOOPS					\
		$MEMTOTAL_ANON 2> /dev/null &
	echo \$! >> $SHELLPACK_TEMP/usemem.pids

	for USEMEM_PID in \`cat $SHELLPACK_TEMP/usemem.pids\`; do
		echo Waiting on pid \$USEMEM_PID
		wait \$USEMEM_PID
	done" > $SHELLPACK_TEMP/usemem.sh
	chmod a+x $SHELLPACK_TEMP/usemem.sh
	$TIME_CMD -o $LOGDIR_RESULTS/usemem-$SWAPPINESS $SHELLPACK_TEMP/usemem.sh
	cat $LOGDIR_RESULTS/usemem-$SWAPPINESS

	kill $PID_VMSTAT
###SHELLPACK threads_stride_end

echo Restoring swappiness value of $ORIGINAL_SWAPPINESS
echo $ORIGINAL_SWAPPINESS > /proc/sys/vm/swappiness

exit $SHELLPACK_SUCCESS

