#!/bin/bash
# libmicro installer
###SHELLPACK preamble libmicro-contextswitch-install 1
GIT_LOCATION=https://github.com/redhat-performance/libMicro
MIRROR_LOCATION="$WEBROOT/extra/libmicro"

install-depends gcc

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch libmicro-contextswitch-${VERSION}.tar.gz libmicro-contextswitch-${VERSION}-installed

###SHELLPACK build_start libmicro-contextswitch-${VERSION}-installed

###SHELLPACK make_clean
###SHELLPACK make

echo libmicro installed successfully
