#!/bin/bash
###SHELLPACK preamble graph500-install graph500-2.1.4
GIT_LOCATION="https://github.com/graph500/graph500"
MIRROR_LOCATION="$WEBROOT/graph500/"

install-depends openmpi openmpi-devel openmpi-libs
install-depends libpsm_infinipath1

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd
###SHELLPACK git_fetch graph500-${VERSION}.tar.bz2 graph500-$VERSION-installed
exit $SHELLPACK_SUCCESS
