#!/bin/bash
###SHELLPACK preamble arraysmash-bench 0

LANGUAGE=perl

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam --language   LANGUAGE
###SHELLPACK parseargParam --arraysize  ARRAYSIZE
###SHELLPACK parseargParam --arraymem   ARRAYMEM
###SHELLPACK parseargParam --iterations ITERATIONS
###SHELLPACK parseargEnd

# Sanity check
if [ "$ARRAYSIZE" = "" ]; then
	if [ "$ARRAYMEM" = "" ]; then
		echo Specified neither ARRAYSIZE or ARRAYMEM
		exit $SHELLPACK_ERROR
	fi
fi

TIME_CMD=`which time`
if [ "$TIME_CMD" = "" ]; then
        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
        TIME_CMD="time"
fi

echo Dumping existing cache
sync
echo 3 > /proc/sys/vm/drop_caches 2> /dev/null
sync

for i in `seq 1 $ITERATIONS`; do
	echo o Iteration $i/$ITERATIONS
	case $LANGUAGE in
	perl)
		if [ "$ARRAYSIZE" = "" ]; then
			INTSIZE=`perl -e 'use Config; print (($Config{nvsize}+$Config{ptrsize})*4)'`
			ARRAYSIZE=$((ARRAYMEM/INTSIZE))
		fi
		$TIME_CMD perl -e "\$num=$ARRAYSIZE;
			@a=(0..\$num);
			foreach \$j (0..4) {
				\$a[\$_] = \$_ foreach (0..\$num);
				\$|=1;
			}" 2>&1 | tee $LOGDIR_RESULTS/time.$i
		;;
	*)
		echo Unrecognised language $LANGUAGE
		exit $SHELLPACK_ERROR
		;;
	esac
done

cat $LOGDIR_RESULTS/time.* | grep elapsed | tee $LOGDIR_RESULTS/time

exit $RETVAL
