#!/bin/bash
# vmscale installer
###SHELLPACK preamble vmscale-install 1
GIT_LOCATION=https://github.com/aristeu/vm-scalability
MIRROR_LOCATION="$WEBROOT/vmscale"

###SHELLPACK parseargBegin
###SHELLPACK parseargEnd

###SHELLPACK git_fetch vmscale-${VERSION}.tar.gz vmscale-${VERSION}-installed

echo vmscale installed successfully
exit $SHELLPACK_SUCCESS
