#!/bin/bash
###SHELLPACK preamble libmicro-regular-bench 1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK check_install_required libmicro-regular-${VERSION}

###SHELLPACK monitor_hooks

cd $SHELLPACK_SOURCES/libmicro-regular-${VERSION}-installed || die Failed to cd to libmicro directory

COMMON="-E -C 2000 -L -S -W"

TMPROOT=/tmp/libmicro.$$
mkdir -p $TMPROOT
trap "rm -rf $TMPROOT" 0 2
IFILE=$TMPROOT/ifile
touch $IFILE

while read A B C; do
	monitor_pre_hook $LOGDIR_RESULTS $B
	if [ -f bin/$A ]; then
		eval bin/$A $COMMON -N "$B" $C 2>&1 > $LOGDIR_RESULTS/$B.log
	fi
	monitor_post_hook $LOGDIR_RESULTS $B
done <<EOT
getpid	getpid	-B 10000
getenv	getenv	-s 100 -B 10000
getenv	getenvT2	-s 100 -B 10000   -T 2
gettimeofday	gettimeofday
log	log	-B 10000
exp	exp	-B 10000
lrand48	lrand48
isatty	isatty_yes
isatty	isatty_no	-f	$IFILE
strtol	strtol	-B 10000
longjmp	longjmp	-B 10000
siglongjmp	siglongjmp	-B 10000
getrusage	getrusage	-B 10000
times	times	-B 10000
time	time	-B 10000
localtime_r	localtime_r	-B 10000
strftime	strftime	-B 10000
mktime	mktime	-B 10000
mktime	mktimeT2	-T 2 -B 10000
EOT

exit $SHELLPACK_SUCCESS
