#!/bin/bash
###SHELLPACK preamble libmicro-regular-bench 1

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargEnd

###SHELLPACK check_install_required libmicro-regular-${VERSION}

###SHELLPACK monitor_hooks

cd $SHELLPACK_SOURCES/libmicro-regular-${VERSION}-installed || die Failed to cd to libmicro directory

COMMON="-E -C 2000 -L -S -W"

TMPROOT=/tmp/libmicro.$$
mkdir -p $TMPROOT
trap "rm -rf $TMPROOT" 0 2
IFILE=$TMPROOT/ifile
touch $IFILE

while read A B C; do
	monitor_pre_hook $LOGDIR_RESULTS $B
	if [ -f bin/$A ]; then
		eval bin/$A $COMMON -N "$B" $C 2>&1 > $LOGDIR_RESULTS/$B.log
	fi
	monitor_post_hook $LOGDIR_RESULTS $B
done <<EOT
getpid	getpid	-I 5
getenv	getenv	-s 100 -I 100
getenv	getenvT2	-s 100 -I 100   -T 2
gettimeofday	gettimeofday
log	log	-I 20
exp	exp	-I 20
lrand48	lrand48
isatty	isatty_yes
isatty	isatty_no	-f	$IFILE
strtol	strtol	-I 20
longjmp	longjmp	-I 10
siglongjmp	siglongjmp	-I 20
getrusage	getrusage	-I 200
times	times	-I 200
time	time	-I 50
localtime_r	localtime_r	-I 200
strftime	strftime	-I 10000
mktime	mktime	-I 500
mktime	mktimeT2	-T 2 -I 1000
EOT

exit $SHELLPACK_SUCCESS
