#!/bin/bash

###SHELLPACK preamble parsec-bench 0

###SHELLPACK parseargBegin
###SHELLPACK parseargInstall
###SHELLPACK parseargParam	--parallel	PARSEC_PARALLEL
###SHELLPACK parseargParam	--iterations    PARSEC_ITERATIONS
###SHELLPACK parseargParam	--size		PARSEC_SIZE
###SHELLPACK parseargParam	--workload	PARSEC_WORKLOAD
###SHELLPACK parseargEnd

###SHELLPACK monitor_hooks

cd $SHELLPACK_SOURCES/parsecbuild-$VERSION-installed || die "Parsec build directory does not exist"
source env.sh || die "Failed to source env.sh"
###SHELLPACK iteration_begin $PARSEC_ITERATIONS
	$TIME_CMD -o $LOGDIR_RESULTS/time.$ITERATION \
		parsecmgmt -a run -c $PARSEC_PARALLEL -i $PARSEC_SIZE -p $PARSEC_WORKLOAD 2>&1 | tee $LOGDIR_RESULTS/parsec.log.$ITERATION
###SHELLPACK iteration_end $PARSEC_ITERATIONS

exit $SHELLPACK_SUCCESS
